In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [52]:
pd.set_option('display.max_rows',100)

In [53]:
rawdata=pd.read_csv("test.csv", delimiter=";" )
rawdata.rename(columns={' ':'Time'},inplace=True)
rawdata['Time']=rawdata['Time'].str.replace('[^\d\:]','')
rawdata['Time']=pd.to_datetime(rawdata.Time)

## Change Date

In [54]:
percent_batt=100

In [55]:
batt=percent_batt*96

## Change Percent Batt

In [56]:
rawdata.set_index('Time', inplace=True)

In [57]:
rawdata.drop(['Total consumption / Mean values [W] ',
       'Grid feed-in / Mean values [W] ',
       'Direct consumption / Mean values [W]  ',
       'Battery charging / Mean values [W]  ',
       'Target value / Mean values [W]  ', 'Output value / Mean values [W]  '],axis=1,inplace=True)

In [58]:
rawdata.loc[rawdata.loc[pd.IndexSlice[:,'Battery discharging / Mean values [W] ']]==' ']
deleteindex=rawdata.loc[rawdata.loc[pd.IndexSlice[:,'Battery discharging / Mean values [W] ']]==' '].index
rawdata.drop(deleteindex,inplace=True)

In [59]:
for i in rawdata.columns:
    rawdata[i].fillna('0',inplace=True)
    rawdata[i]=rawdata[i].apply(lambda x: x.replace(' ', '0'))
    rawdata[i]=rawdata[i].str.replace('\D','').astype(int)

In [60]:
rawdata.columns

Index(['Direct consumption / Mean values [W] ',
       'Battery discharging / Mean values [W] ',
       'External energy supply / Mean values [W] ',
       'PV power generation / Mean values [W]  '],
      dtype='object')

In [61]:
rawdata['Consumption']=rawdata['Direct consumption / Mean values [W] ']+rawdata['Battery discharging / Mean values [W] ']+rawdata['External energy supply / Mean values [W] ']
rawdata.rename(columns={'PV power generation / Mean values [W]  ':'Generation'},inplace=True)
rawdata.drop(['Direct consumption / Mean values [W] ', 'Battery discharging / Mean values [W] ','External energy supply / Mean values [W] '],axis=1,inplace=True)

Have Data with Generation and Consumption

In [62]:
rawdata

                     Generation  Consumption
Time
2019-02-12 00:15:00           0         1869
2019-02-12 00:30:00           0         1881
2019-02-12 00:45:00           0         1648
2019-02-12 01:00:00           0         1806
2019-02-12 01:15:00           0         1839
2019-02-12 01:30:00           0         1781
2019-02-12 01:45:00           0         1492
2019-02-12 02:00:00           0         1725
2019-02-12 02:15:00           0         1246
2019-02-12 02:30:00           0         1334
2019-02-12 02:45:00           0         1376
2019-02-12 03:00:00           0         1062
2019-02-12 03:15:00           0         1356
2019-02-12 03:30:00           0          893
2019-02-12 03:45:00           0         1413
2019-02-12 04:00:00           0          968
2019-02-12 04:15:00           0         1246
2019-02-12 04:30:00           0          965
2019-02-12 04:45:00           0          975
2019-02-12 05:00:00           0         1089
2019-02-12 05:15:00           0         2204
2019-02-12 05:30:00           0         2894
2019-02-12 05:45:00           0         2151
2019-02-12 06:00:00           0         1297
2019-02-12 06:15:00           0         1140
2019-02-12 06:30:00           0         2041
2019-02-12 06:45:00          10         1434
2019-02-12 07:00:00          74         1097
2019-02-12 07:15:00         174         1057
2019-02-12 07:30:00         410         1179
2019-02-12 07:45:00         562         1176
2019-02-12 08:00:00         710         1487
2019-02-12 08:15:00         925         1202
2019-02-12 08:30:00        1121         1135
2019-02-12 08:45:00        1407          994
2019-02-12 09:00:00        1656         1005
2019-02-12 09:15:00        2009          940
2019-02-12 09:30:00        2181          629
2019-02-12 09:45:00        2288          938
2019-02-12 10:00:00        2363         1402
2019-02-12 10:15:00        2107          866
2019-02-12 10:30:00        2542         2874
2019-02-12 10:45:00        2334         2273
2019-02-12 11:00:00        2331         2189
2019-02-12 11:15:00        2270         2047
2019-02-12 11:30:00        2314         2070
2019-02-12 11:45:00        2200         1910
2019-02-12 12:00:00        1835          967
2019-02-12 12:15:00        1677          885
2019-02-12 12:30:00        1592          938
2019-02-12 12:45:00        1435          856
2019-02-12 13:00:00        2270         1954
2019-02-12 13:15:00        2214         1926
2019-02-12 13:30:00        2112         1631
2019-02-12 13:45:00        2153         1727
2019-02-12 14:00:00        1999         1718
2019-02-12 14:15:00        1844         1581
2019-02-12 14:30:00        1610         1541
2019-02-12 14:45:00        1499         1522
2019-02-12 15:00:00        1299         1437
2019-02-12 15:15:00        1159         1837
2019-02-12 15:30:00        1005         2605
2019-02-12 15:45:00         955          951
2019-02-12 16:00:00         874          837
2019-02-12 16:15:00         546          848
2019-02-12 16:30:00         342          920
2019-02-12 16:45:00         303          909
2019-02-12 17:00:00         199         1331
2019-02-12 17:15:00         133         2112
2019-02-12 17:30:00         104         1669
2019-02-12 17:45:00          19         1604
2019-02-12 18:00:00           0         2232
2019-02-12 18:15:00           0         1562
2019-02-12 18:30:00           0         2163
2019-02-12 18:45:00           0         1640
2019-02-12 19:00:00           0         1519
2019-02-12 19:15:00           0         2409
2019-02-12 19:30:00           0         3430
2019-02-12 19:45:00           0         3160
2019-02-12 20:00:00           0         3755
2019-02-12 20:15:00           0         3530
2019-02-12 20:30:00           0         3659
2019-02-12 20:45:00           0         4775
2019-02-12 21:00:00           0         4459
2019-02-12 21:15:00           0         4366
2019-02-12 21:30:00           0         3445
2019-02-12 21:45:00           0         2762
2019-02-12 22:00:00           0         2355
2019-02-12 22:15:00           0         2829
2019-02-12 22:30:00           0         2092
2019-02-12 22:45:00           0         2373
2019-02-12 23:00:00           0         2518
2019-02-12 23:15:00           0         1696
2019-02-12 23:30:00           0         2198
2019-02-12 23:45:00           0         1767

In [63]:
rawdata.index
Consumption_afterPV=[]
Charge=[]
for i in rawdata.index:
    if rawdata.loc[i,'Generation']>=rawdata.loc[i,'Consumption']:
        Charge.append(rawdata.loc[i,'Generation']-rawdata.loc[i,'Consumption'])
        Consumption_afterPV.append(0)
    else:
        Charge.append(0)
        Consumption_afterPV.append(rawdata.loc[i,'Consumption']-rawdata.loc[i,'Generation'])

In [64]:
rawdata['Charge']=Charge
rawdata['Consumption_afterPV']=Consumption_afterPV

In [65]:
totalcharge=rawdata['Charge'].sum()
totalcharge

13255

In [66]:
data=rawdata

In [67]:
peakloadtotal=0
data

                     Generation  Consumption  Charge  Consumption_afterPV
Time
2019-02-12 00:15:00           0         1869       0                 1869
2019-02-12 00:30:00           0         1881       0                 1881
2019-02-12 00:45:00           0         1648       0                 1648
2019-02-12 01:00:00           0         1806       0                 1806
2019-02-12 01:15:00           0         1839       0                 1839
2019-02-12 01:30:00           0         1781       0                 1781
2019-02-12 01:45:00           0         1492       0                 1492
2019-02-12 02:00:00           0         1725       0                 1725
2019-02-12 02:15:00           0         1246       0                 1246
2019-02-12 02:30:00           0         1334       0                 1334
2019-02-12 02:45:00           0         1376       0                 1376
2019-02-12 03:00:00           0         1062       0                 1062
2019-02-12 03:15:00           0         1356       0                 1356
2019-02-12 03:30:00           0          893       0                  893
2019-02-12 03:45:00           0         1413       0                 1413
2019-02-12 04:00:00           0          968       0                  968
2019-02-12 04:15:00           0         1246       0                 1246
2019-02-12 04:30:00           0          965       0                  965
2019-02-12 04:45:00           0          975       0                  975
2019-02-12 05:00:00           0         1089       0                 1089
2019-02-12 05:15:00           0         2204       0                 2204
2019-02-12 05:30:00           0         2894       0                 2894
2019-02-12 05:45:00           0         2151       0                 2151
2019-02-12 06:00:00           0         1297       0                 1297
2019-02-12 06:15:00           0         1140       0                 1140
2019-02-12 06:30:00           0         2041       0                 2041
2019-02-12 06:45:00          10         1434       0                 1424
2019-02-12 07:00:00          74         1097       0                 1023
2019-02-12 07:15:00         174         1057       0                  883
2019-02-12 07:30:00         410         1179       0                  769
2019-02-12 07:45:00         562         1176       0                  614
2019-02-12 08:00:00         710         1487       0                  777
2019-02-12 08:15:00         925         1202       0                  277
2019-02-12 08:30:00        1121         1135       0                   14
2019-02-12 08:45:00        1407          994     413                    0
2019-02-12 09:00:00        1656         1005     651                    0
2019-02-12 09:15:00        2009          940    1069                    0
2019-02-12 09:30:00        2181          629    1552                    0
2019-02-12 09:45:00        2288          938    1350                    0
2019-02-12 10:00:00        2363         1402     961                    0
2019-02-12 10:15:00        2107          866    1241                    0
2019-02-12 10:30:00        2542         2874       0                  332
2019-02-12 10:45:00        2334         2273      61                    0
2019-02-12 11:00:00        2331         2189     142                    0
2019-02-12 11:15:00        2270         2047     223                    0
2019-02-12 11:30:00        2314         2070     244                    0
2019-02-12 11:45:00        2200         1910     290                    0
2019-02-12 12:00:00        1835          967     868                    0
2019-02-12 12:15:00        1677          885     792                    0
2019-02-12 12:30:00        1592          938     654                    0
2019-02-12 12:45:00        1435          856     579                    0
2019-02-12 13:00:00        2270         1954     316                    0
2019-02-12 13:15:00        2214         1926     288                    0
2019-02-12 13:30:00        2112         1631     481                    0
2019-02-12 13:45:00        2153         1727     426                    0
2019-02-12 14:00:00        1999         1718     281                    0
2019-02-12 14:15:00        1844         1581     263                    0
2019-02-12 14:30:00        1610         1541      69                    0
2019-02-12 14:45:00        1499         1522       0                   23
2019-02-12 15:00:00        1299         1437       0                  138
2019-02-12 15:15:00        1159         1837       0                  678
2019-02-12 15:30:00        1005         2605       0                 1600
2019-02-12 15:45:00         955          951       4                    0
2019-02-12 16:00:00         874          837      37                    0
2019-02-12 16:15:00         546          848       0                  302
2019-02-12 16:30:00         342          920       0                  578
2019-02-12 16:45:00         303          909       0                  606
2019-02-12 17:00:00         199         1331       0                 1132
2019-02-12 17:15:00         133         2112       0                 1979
2019-02-12 17:30:00         104         1669       0                 1565
2019-02-12 17:45:00          19         1604       0                 1585
2019-02-12 18:00:00           0         2232       0                 2232
2019-02-12 18:15:00           0         1562       0                 1562
2019-02-12 18:30:00           0         2163       0                 2163
2019-02-12 18:45:00           0         1640       0                 1640
2019-02-12 19:00:00           0         1519       0                 1519
2019-02-12 19:15:00           0         2409       0                 2409
2019-02-12 19:30:00           0         3430       0                 3430
2019-02-12 19:45:00           0         3160       0                 3160
2019-02-12 20:00:00           0         3755       0                 3755
2019-02-12 20:15:00           0         3530       0                 3530
2019-02-12 20:30:00           0         3659       0                 3659
2019-02-12 20:45:00           0         4775       0                 4775
2019-02-12 21:00:00           0         4459       0                 4459
2019-02-12 21:15:00           0         4366       0                 4366
2019-02-12 21:30:00           0         3445       0                 3445
2019-02-12 21:45:00           0         2762       0                 2762
2019-02-12 22:00:00           0         2355       0                 2355
2019-02-12 22:15:00           0         2829       0                 2829
2019-02-12 22:30:00           0         2092       0                 2092
2019-02-12 22:45:00           0         2373       0                 2373
2019-02-12 23:00:00           0         2518       0                 2518
2019-02-12 23:15:00           0         1696       0                 1696
2019-02-12 23:30:00           0         2198       0                 2198
2019-02-12 23:45:00           0         1767       0                 1767

In [68]:
for i in range(1,96):
    peakloaddf=data.nlargest(i,columns='Consumption_afterPV').Consumption_afterPV
    #print(peakloaddf)
    peakload=peakloaddf.iloc[i-1:i]
    peakloadtotal += peakload.iloc[0]
    print(peakload)
    #print(peakloadtotal)
    if peakloadtotal>=totalcharge:
        remain=(peakloadtotal-totalcharge)
        print(remain)
        for j in peakloaddf.index:
            data.loc[j:j,'Consumption_afterPV']=0
        data.loc[peakload.index,'Consumption_afterPV']=remain
        break

Time
2019-02-12 20:45:00    4775
Name: Consumption_afterPV, dtype: int64
Time
2019-02-12 21:00:00    4459
Name: Consumption_afterPV, dtype: int64
Time
2019-02-12 21:15:00    4366
Name: Consumption_afterPV, dtype: int64
345

In [69]:
data

                     Generation  Consumption  Charge  Consumption_afterPV
Time
2019-02-12 00:15:00           0         1869       0                 1869
2019-02-12 00:30:00           0         1881       0                 1881
2019-02-12 00:45:00           0         1648       0                 1648
2019-02-12 01:00:00           0         1806       0                 1806
2019-02-12 01:15:00           0         1839       0                 1839
2019-02-12 01:30:00           0         1781       0                 1781
2019-02-12 01:45:00           0         1492       0                 1492
2019-02-12 02:00:00           0         1725       0                 1725
2019-02-12 02:15:00           0         1246       0                 1246
2019-02-12 02:30:00           0         1334       0                 1334
2019-02-12 02:45:00           0         1376       0                 1376
2019-02-12 03:00:00           0         1062       0                 1062
2019-02-12 03:15:00           0         1356       0                 1356
2019-02-12 03:30:00           0          893       0                  893
2019-02-12 03:45:00           0         1413       0                 1413
2019-02-12 04:00:00           0          968       0                  968
2019-02-12 04:15:00           0         1246       0                 1246
2019-02-12 04:30:00           0          965       0                  965
2019-02-12 04:45:00           0          975       0                  975
2019-02-12 05:00:00           0         1089       0                 1089
2019-02-12 05:15:00           0         2204       0                 2204
2019-02-12 05:30:00           0         2894       0                 2894
2019-02-12 05:45:00           0         2151       0                 2151
2019-02-12 06:00:00           0         1297       0                 1297
2019-02-12 06:15:00           0         1140       0                 1140
2019-02-12 06:30:00           0         2041       0                 2041
2019-02-12 06:45:00          10         1434       0                 1424
2019-02-12 07:00:00          74         1097       0                 1023
2019-02-12 07:15:00         174         1057       0                  883
2019-02-12 07:30:00         410         1179       0                  769
2019-02-12 07:45:00         562         1176       0                  614
2019-02-12 08:00:00         710         1487       0                  777
2019-02-12 08:15:00         925         1202       0                  277
2019-02-12 08:30:00        1121         1135       0                   14
2019-02-12 08:45:00        1407          994     413                    0
2019-02-12 09:00:00        1656         1005     651                    0
2019-02-12 09:15:00        2009          940    1069                    0
2019-02-12 09:30:00        2181          629    1552                    0
2019-02-12 09:45:00        2288          938    1350                    0
2019-02-12 10:00:00        2363         1402     961                    0
2019-02-12 10:15:00        2107          866    1241                    0
2019-02-12 10:30:00        2542         2874       0                  332
2019-02-12 10:45:00        2334         2273      61                    0
2019-02-12 11:00:00        2331         2189     142                    0
2019-02-12 11:15:00        2270         2047     223                    0
2019-02-12 11:30:00        2314         2070     244                    0
2019-02-12 11:45:00        2200         1910     290                    0
2019-02-12 12:00:00        1835          967     868                    0
2019-02-12 12:15:00        1677          885     792                    0
2019-02-12 12:30:00        1592          938     654                    0
2019-02-12 12:45:00        1435          856     579                    0
2019-02-12 13:00:00        2270         1954     316                    0
2019-02-12 13:15:00        2214         1926     288                    0
2019-02-12 13:30:00        2112         1631     481                    0
2019-02-12 13:45:00        2153         1727     426                    0
2019-02-12 14:00:00        1999         1718     281                    0
2019-02-12 14:15:00        1844         1581     263                    0
2019-02-12 14:30:00        1610         1541      69                    0
2019-02-12 14:45:00        1499         1522       0                   23
2019-02-12 15:00:00        1299         1437       0                  138
2019-02-12 15:15:00        1159         1837       0                  678
2019-02-12 15:30:00        1005         2605       0                 1600
2019-02-12 15:45:00         955          951       4                    0
2019-02-12 16:00:00         874          837      37                    0
2019-02-12 16:15:00         546          848       0                  302
2019-02-12 16:30:00         342          920       0                  578
2019-02-12 16:45:00         303          909       0                  606
2019-02-12 17:00:00         199         1331       0                 1132
2019-02-12 17:15:00         133         2112       0                 1979
2019-02-12 17:30:00         104         1669       0                 1565
2019-02-12 17:45:00          19         1604       0                 1585
2019-02-12 18:00:00           0         2232       0                 2232
2019-02-12 18:15:00           0         1562       0                 1562
2019-02-12 18:30:00           0         2163       0                 2163
2019-02-12 18:45:00           0         1640       0                 1640
2019-02-12 19:00:00           0         1519       0                 1519
2019-02-12 19:15:00           0         2409       0                 2409
2019-02-12 19:30:00           0         3430       0                 3430
2019-02-12 19:45:00           0         3160       0                 3160
2019-02-12 20:00:00           0         3755       0                 3755
2019-02-12 20:15:00           0         3530       0                 3530
2019-02-12 20:30:00           0         3659       0                 3659
2019-02-12 20:45:00           0         4775       0                    0
2019-02-12 21:00:00           0         4459       0                    0
2019-02-12 21:15:00           0         4366       0                  345
2019-02-12 21:30:00           0         3445       0                 3445
2019-02-12 21:45:00           0         2762       0                 2762
2019-02-12 22:00:00           0         2355       0                 2355
2019-02-12 22:15:00           0         2829       0                 2829
2019-02-12 22:30:00           0         2092       0                 2092
2019-02-12 22:45:00           0         2373       0                 2373
2019-02-12 23:00:00           0         2518       0                 2518
2019-02-12 23:15:00           0         1696       0                 1696
2019-02-12 23:30:00           0         2198       0                 2198
2019-02-12 23:45:00           0         1767       0                 1767

In [70]:
peakloaddf

Time
2019-02-12 20:45:00    4775
2019-02-12 21:00:00    4459
2019-02-12 21:15:00    4366
Name: Consumption_afterPV, dtype: int64

In [71]:
data['Discharge']=data.Consumption_afterPV*0
for i in peakloaddf.index:
    data.loc[i:i,'Discharge']=data.loc[i:i,'Consumption']-data.loc[i:i,'Generation']-data.loc[i:i,'Consumption_afterPV']

In [72]:
data

,Generation,Consumption,Charge,Consumption_afterPV,Discharge
Time,,,,,
2019-02-12 00:15:00,0,1869,0,1869,0
2019-02-12 00:30:00,0,1881,0,1881,0
2019-02-12 00:45:00,0,1648,0,1648,0
2019-02-12 01:00:00,0,1806,0,1806,0
2019-02-12 01:15:00,0,1839,0,1839,0
2019-02-12 01:30:00,0,1781,0,1781,0
2019-02-12 01:45:00,0,1492,0,1492,0
2019-02-12 02:00:00,0,1725,0,1725,0
2019-02-12 02:15:00,0,1246,0,1246,0
2019-02-12 02:30:00,0,1334,0,1334,0
2019-02-12 02:45:00,0,1376,0,1376,0
2019-02-12 03:00:00,0,1062,0,1062,0
2019-02-12 03:15:00,0,1356,0,1356,0
2019-02-12 03:30:00,0,893,0,893,0
2019-02-12 03:45:00,0,1413,0,1413,0
2019-02-12 04:00:00,0,968,0,968,0
2019-02-12 04:15:00,0,1246,0,1246,0
2019-02-12 04:30:00,0,965,0,965,0
2019-02-12 04:45:00,0,975,0,975,0
2019-02-12 05:00:00,0,1089,0,1089,0
2019-02-12 05:15:00,0,2204,0,2204,0
2019-02-12 05:30:00,0,2894,0,2894,0
2019-02-12 05:45:00,0,2151,0,2151,0
2019-02-12 06:00:00,0,1297,0,1297,0
2019-02-12 06:15:00,0,1140,0,1140,0
2019-02-12 06:30:00,0,2041,0,2041,0
2019-02-12 06:45:00,10,1434,0,1424,0
2019-02-12 07:00:00,74,1097,0,1023,0
2019-02-12 07:15:00,174,1057,0,883,0
2019-02-12 07:30:00,410,1179,0,769,0
2019-02-12 07:45:00,562,1176,0,614,0
2019-02-12 08:00:00,710,1487,0,777,0
2019-02-12 08:15:00,925,1202,0,277,0
2019-02-12 08:30:00,1121,1135,0,14,0
2019-02-12 08:45:00,1407,994,413,0,0
2019-02-12 09:00:00,1656,1005,651,0,0
2019-02-12 09:15:00,2009,940,1069,0,0
2019-02-12 09:30:00,2181,629,1552,0,0
2019-02-12 09:45:00,2288,938,1350,0,0
2019-02-12 10:00:00,2363,1402,961,0,0
2019-02-12 10:15:00,2107,866,1241,0,0
2019-02-12 10:30:00,2542,2874,0,332,0
2019-02-12 10:45:00,2334,2273,61,0,0
2019-02-12 11:00:00,2331,2189,142,0,0
2019-02-12 11:15:00,2270,2047,223,0,0
2019-02-12 11:30:00,2314,2070,244,0,0
2019-02-12 11:45:00,2200,1910,290,0,0
2019-02-12 12:00:00,1835,967,868,0,0
2019-02-12 12:15:00,1677,885,792,0,0
2019-02-12 12:30:00,1592,938,654,0,0
2019-02-12 12:45:00,1435,856,579,0,0
2019-02-12 13:00:00,2270,1954,316,0,0
2019-02-12 13:15:00,2214,1926,288,0,0
2019-02-12 13:30:00,2112,1631,481,0,0
2019-02-12 13:45:00,2153,1727,426,0,0
2019-02-12 14:00:00,1999,1718,281,0,0
2019-02-12 14:15:00,1844,1581,263,0,0
2019-02-12 14:30:00,1610,1541,69,0,0
2019-02-12 14:45:00,1499,1522,0,23,0
2019-02-12 15:00:00,1299,1437,0,138,0
2019-02-12 15:15:00,1159,1837,0,678,0
2019-02-12 15:30:00,1005,2605,0,1600,0
2019-02-12 15:45:00,955,951,4,0,0
2019-02-12 16:00:00,874,837,37,0,0
2019-02-12 16:15:00,546,848,0,302,0
2019-02-12 16:30:00,342,920,0,578,0
2019-02-12 16:45:00,303,909,0,606,0
2019-02-12 17:00:00,199,1331,0,1132,0
2019-02-12 17:15:00,133,2112,0,1979,0
2019-02-12 17:30:00,104,1669,0,1565,0
2019-02-12 17:45:00,19,1604,0,1585,0
2019-02-12 18:00:00,0,2232,0,2232,0
2019-02-12 18:15:00,0,1562,0,1562,0
2019-02-12 18:30:00,0,2163,0,2163,0
2019-02-12 18:45:00,0,1640,0,1640,0
2019-02-12 19:00:00,0,1519,0,1519,0
2019-02-12 19:15:00,0,2409,0,2409,0
2019-02-12 19:30:00,0,3430,0,3430,0
2019-02-12 19:45:00,0,3160,0,3160,0
2019-02-12 20:00:00,0,3755,0,3755,0
2019-02-12 20:15:00,0,3530,0,3530,0
2019-02-12 20:30:00,0,3659,0,3659,0
2019-02-12 20:45:00,0,4775,0,0,4775
2019-02-12 21:00:00,0,4459,0,0,4459
2019-02-12 21:15:00,0,4366,0,345,4021
2019-02-12 21:30:00,0,3445,0,3445,0
2019-02-12 21:45:00,0,2762,0,2762,0
2019-02-12 22:00:00,0,2355,0,2355,0
2019-02-12 22:15:00,0,2829,0,2829,0
2019-02-12 22:30:00,0,2092,0,2092,0
2019-02-12 22:45:00,0,2373,0,2373,0
2019-02-12 23:00:00,0,2518,0,2518,0
2019-02-12 23:15:00,0,1696,0,1696,0
2019-02-12 23:30:00,0,2198,0,2198,0
2019-02-12 23:45:00,0,1767,0,1767,0

In [77]:
Contactor=[]
for i in data.index:
    if data.loc[i,'Charge']>0:
        Contactor.append(1)
    elif data.loc[i,'Discharge']>0:
        Contactor.append(1)
    else:
        Contactor.append(0)
data['Contactor']=Contactor
data

,Generation,Consumption,Charge,Consumption_afterPV,Discharge,Contactor
Time,,,,,,
2019-02-12 00:15:00,0,1869,0,1869,0,0
2019-02-12 00:30:00,0,1881,0,1881,0,0
2019-02-12 00:45:00,0,1648,0,1648,0,0
2019-02-12 01:00:00,0,1806,0,1806,0,0
2019-02-12 01:15:00,0,1839,0,1839,0,0
2019-02-12 01:30:00,0,1781,0,1781,0,0
2019-02-12 01:45:00,0,1492,0,1492,0,0
2019-02-12 02:00:00,0,1725,0,1725,0,0
2019-02-12 02:15:00,0,1246,0,1246,0,0
2019-02-12 02:30:00,0,1334,0,1334,0,0
2019-02-12 02:45:00,0,1376,0,1376,0,0
2019-02-12 03:00:00,0,1062,0,1062,0,0
2019-02-12 03:15:00,0,1356,0,1356,0,0
2019-02-12 03:30:00,0,893,0,893,0,0
2019-02-12 03:45:00,0,1413,0,1413,0,0
2019-02-12 04:00:00,0,968,0,968,0,0
2019-02-12 04:15:00,0,1246,0,1246,0,0
2019-02-12 04:30:00,0,965,0,965,0,0
2019-02-12 04:45:00,0,975,0,975,0,0
2019-02-12 05:00:00,0,1089,0,1089,0,0
2019-02-12 05:15:00,0,2204,0,2204,0,0
2019-02-12 05:30:00,0,2894,0,2894,0,0
2019-02-12 05:45:00,0,2151,0,2151,0,0
2019-02-12 06:00:00,0,1297,0,1297,0,0
2019-02-12 06:15:00,0,1140,0,1140,0,0
2019-02-12 06:30:00,0,2041,0,2041,0,0
2019-02-12 06:45:00,10,1434,0,1424,0,0
2019-02-12 07:00:00,74,1097,0,1023,0,0
2019-02-12 07:15:00,174,1057,0,883,0,0
2019-02-12 07:30:00,410,1179,0,769,0,0
2019-02-12 07:45:00,562,1176,0,614,0,0
2019-02-12 08:00:00,710,1487,0,777,0,0
2019-02-12 08:15:00,925,1202,0,277,0,0
2019-02-12 08:30:00,1121,1135,0,14,0,0
2019-02-12 08:45:00,1407,994,413,0,0,1
2019-02-12 09:00:00,1656,1005,651,0,0,1
2019-02-12 09:15:00,2009,940,1069,0,0,1
2019-02-12 09:30:00,2181,629,1552,0,0,1
2019-02-12 09:45:00,2288,938,1350,0,0,1
2019-02-12 10:00:00,2363,1402,961,0,0,1
2019-02-12 10:15:00,2107,866,1241,0,0,1
2019-02-12 10:30:00,2542,2874,0,332,0,0
2019-02-12 10:45:00,2334,2273,61,0,0,1
2019-02-12 11:00:00,2331,2189,142,0,0,1
2019-02-12 11:15:00,2270,2047,223,0,0,1
2019-02-12 11:30:00,2314,2070,244,0,0,1
2019-02-12 11:45:00,2200,1910,290,0,0,1
2019-02-12 12:00:00,1835,967,868,0,0,1
2019-02-12 12:15:00,1677,885,792,0,0,1
2019-02-12 12:30:00,1592,938,654,0,0,1
2019-02-12 12:45:00,1435,856,579,0,0,1
2019-02-12 13:00:00,2270,1954,316,0,0,1
2019-02-12 13:15:00,2214,1926,288,0,0,1
2019-02-12 13:30:00,2112,1631,481,0,0,1
2019-02-12 13:45:00,2153,1727,426,0,0,1
2019-02-12 14:00:00,1999,1718,281,0,0,1
2019-02-12 14:15:00,1844,1581,263,0,0,1
2019-02-12 14:30:00,1610,1541,69,0,0,1
2019-02-12 14:45:00,1499,1522,0,23,0,0
2019-02-12 15:00:00,1299,1437,0,138,0,0
2019-02-12 15:15:00,1159,1837,0,678,0,0
2019-02-12 15:30:00,1005,2605,0,1600,0,0
2019-02-12 15:45:00,955,951,4,0,0,1
2019-02-12 16:00:00,874,837,37,0,0,1
2019-02-12 16:15:00,546,848,0,302,0,0
2019-02-12 16:30:00,342,920,0,578,0,0
2019-02-12 16:45:00,303,909,0,606,0,0
2019-02-12 17:00:00,199,1331,0,1132,0,0
2019-02-12 17:15:00,133,2112,0,1979,0,0
2019-02-12 17:30:00,104,1669,0,1565,0,0
2019-02-12 17:45:00,19,1604,0,1585,0,0
2019-02-12 18:00:00,0,2232,0,2232,0,0
2019-02-12 18:15:00,0,1562,0,1562,0,0
2019-02-12 18:30:00,0,2163,0,2163,0,0
2019-02-12 18:45:00,0,1640,0,1640,0,0
2019-02-12 19:00:00,0,1519,0,1519,0,0
2019-02-12 19:15:00,0,2409,0,2409,0,0
2019-02-12 19:30:00,0,3430,0,3430,0,0
2019-02-12 19:45:00,0,3160,0,3160,0,0
2019-02-12 20:00:00,0,3755,0,3755,0,0
2019-02-12 20:15:00,0,3530,0,3530,0,0
2019-02-12 20:30:00,0,3659,0,3659,0,0
2019-02-12 20:45:00,0,4775,0,0,4775,1
2019-02-12 21:00:00,0,4459,0,0,4459,1
2019-02-12 21:15:00,0,4366,0,345,4021,1
2019-02-12 21:30:00,0,3445,0,3445,0,0
2019-02-12 21:45:00,0,2762,0,2762,0,0
2019-02-12 22:00:00,0,2355,0,2355,0,0
2019-02-12 22:15:00,0,2829,0,2829,0,0
2019-02-12 22:30:00,0,2092,0,2092,0,0
2019-02-12 22:45:00,0,2373,0,2373,0,0
2019-02-12 23:00:00,0,2518,0,2518,0,0
2019-02-12 23:15:00,0,1696,0,1696,0,0
2019-02-12 23:30:00,0,2198,0,2198,0,0
2019-02-12 23:45:00,0,1767,0,1767,0,0

## Problem rawdata update info about algorithm