## Algorithm mode duty cycle

## Missing Data Problem

In [77]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format='retina'

In [78]:
pd.set_option('display.max_rows',100)

In [79]:
rawdata=pd.read_csv("Energy_Balance_2018_11_02.csv", delimiter=";" )
rawdata.rename(columns={' ':'Time'},inplace=True)
rawdata['Time']=rawdata['Time'].str.replace('[^\d\:]','')
rawdata['Time']=pd.to_datetime(rawdata.Time)

## Change Date

In [80]:
percent_batt=100

In [81]:
batt=percent_batt*96

## Change Percent Batt

In [82]:
rawdata.set_index('Time', inplace=True)

In [83]:
rawdata.drop(['Total consumption / Mean values [W] ',
       'Grid feed-in / Mean values [W] ',
       'Direct consumption / Mean values [W]  ',
       'Battery charging / Mean values [W]  ',
       'Target value / Mean values [W]  ', 'Output value / Mean values [W]  '],axis=1,inplace=True)

In [84]:
rawdata.loc[rawdata.loc[pd.IndexSlice[:,'Battery discharging / Mean values [W] ']]==' ']
deleteindex=rawdata.loc[rawdata.loc[pd.IndexSlice[:,'Battery discharging / Mean values [W] ']]==' '].index
rawdata.drop(deleteindex,inplace=True)

In [85]:
for i in rawdata.columns:
    rawdata[i].fillna('0',inplace=True)
    rawdata[i]=rawdata[i].apply(lambda x: x.replace(' ', '0'))
    rawdata[i]=rawdata[i].str.replace('\D','').astype(int)

In [86]:
rawdata.columns

Index(['Direct consumption / Mean values [W] ',
       'Battery discharging / Mean values [W] ',
       'External energy supply / Mean values [W] ',
       'PV power generation / Mean values [W]  '],
      dtype='object')

In [87]:
rawdata['Consumption']=rawdata['Direct consumption / Mean values [W] ']+rawdata['Battery discharging / Mean values [W] ']+rawdata['External energy supply / Mean values [W] ']
rawdata.rename(columns={'PV power generation / Mean values [W]  ':'Generation'},inplace=True)
rawdata.drop(['Direct consumption / Mean values [W] ', 'Battery discharging / Mean values [W] ','External energy supply / Mean values [W] '],axis=1,inplace=True)

Have Data with Generation and Consumption

In [88]:
rawdata

                     Generation  Consumption
Time
2019-03-14 00:15:00           0         1562
2019-03-14 00:30:00           0         1662
2019-03-14 00:45:00           0         1623
2019-03-14 01:00:00           0         1421
2019-03-14 01:15:00           0         1160
2019-03-14 01:30:00           0          987
2019-03-14 01:45:00           0         1422
2019-03-14 02:00:00           0         1352
2019-03-14 02:15:00           0          903
2019-03-14 02:30:00           0          974
2019-03-14 02:45:00           0         1237
2019-03-14 03:00:00           0          892
2019-03-14 03:15:00           0          874
2019-03-14 03:30:00           0         1219
2019-03-14 03:45:00           0         1100
2019-03-14 04:00:00           0          853
2019-03-14 04:15:00           0          775
2019-03-14 04:30:00           0         1108
2019-03-14 04:45:00           0          683
2019-03-14 05:00:00           0          895
2019-03-14 05:15:00           0         1892
2019-03-14 05:30:00           0         3617
2019-03-14 05:45:00           0         2147
2019-03-14 06:00:00           0         1098
2019-03-14 06:15:00           0          996
2019-03-14 06:30:00           1         2066
2019-03-14 06:45:00          67         1126
2019-03-14 07:00:00         130         1544
2019-03-14 07:15:00         354          749
2019-03-14 07:30:00         579         1078
2019-03-14 07:45:00         700         1016
2019-03-14 08:00:00         924          982
2019-03-14 08:15:00        1083         1078
2019-03-14 08:30:00        1424         1796
2019-03-14 08:45:00        1631         1278
2019-03-14 09:00:00        1966         1075
2019-03-14 09:15:00        2181          772
2019-03-14 09:30:00        2293          722
2019-03-14 09:45:00        2454          563
2019-03-14 10:00:00        2542          611
2019-03-14 10:15:00        2460          784
2019-03-14 10:30:00        2174         2705
2019-03-14 10:45:00        2348         1779
2019-03-14 11:00:00        2267         1432
2019-03-14 11:15:00        2198         1657
2019-03-14 11:30:00        2065         1467
2019-03-14 11:45:00        1568          752
2019-03-14 12:00:00        1572          877
2019-03-14 12:15:00        1353          765
2019-03-14 12:30:00        1358          845
2019-03-14 12:45:00        1341          860
2019-03-14 13:00:00        1270          817
2019-03-14 13:15:00        1175          738
2019-03-14 13:30:00        1105          679
2019-03-14 13:45:00        1207          811
2019-03-14 14:00:00        1225          827
2019-03-14 14:15:00        1121          709
2019-03-14 14:30:00        1027          688
2019-03-14 14:45:00        1132          818
2019-03-14 15:00:00        1161          860
2019-03-14 15:15:00        1094          802
2019-03-14 15:30:00        1008         1603
2019-03-14 15:45:00         868         1091
2019-03-14 16:00:00         698          947
2019-03-14 16:15:00         492          923
2019-03-14 16:30:00         376          822
2019-03-14 16:45:00         249          723
2019-03-14 17:00:00         147         1553
2019-03-14 17:15:00         101         2005
2019-03-14 17:30:00          58         1675
2019-03-14 17:45:00          26         1679
2019-03-14 18:00:00           2         1555
2019-03-14 18:15:00           0         2453
2019-03-14 18:30:00           0         3079
2019-03-14 18:45:00           0         1772
2019-03-14 19:00:00           0         2943
2019-03-14 19:15:00           0         1999
2019-03-14 19:30:00           0         2224
2019-03-14 19:45:00           0         2778
2019-03-14 20:00:00           0         3024
2019-03-14 20:15:00           0         3021
2019-03-14 20:30:00           0         2604
2019-03-14 20:45:00           0         4046
2019-03-14 21:00:00           0         2689
2019-03-14 21:15:00           0         2857
2019-03-14 21:30:00           0         2820
2019-03-14 21:45:00           0         2096
2019-03-14 22:00:00           0         2373
2019-03-14 22:15:00           0         2160
2019-03-14 22:30:00           0         2074
2019-03-14 22:45:00           0         4348
2019-03-14 23:00:00           0         2792
2019-03-14 23:15:00           0         3449
2019-03-14 23:30:00           0         2367
2019-03-14 23:45:00           0         1857

In [89]:
len(rawdata.index)

95

In [90]:
rawdata.index
Consumption_afterPV=[]
Charge=[]
for i in rawdata.index:
    if rawdata.loc[i,'Generation']>=rawdata.loc[i,'Consumption']:
        Charge.append(rawdata.loc[i,'Generation']-rawdata.loc[i,'Consumption'])
        Consumption_afterPV.append(0)
    else:
        Charge.append(0)
        Consumption_afterPV.append(rawdata.loc[i,'Consumption']-rawdata.loc[i,'Generation'])

In [91]:
rawdata['Charge']=Charge
rawdata['Consumption_afterPV']=Consumption_afterPV

In [92]:
rawdata

                     Generation  Consumption  Charge  Consumption_afterPV
Time
2019-03-14 00:15:00           0         1562       0                 1562
2019-03-14 00:30:00           0         1662       0                 1662
2019-03-14 00:45:00           0         1623       0                 1623
2019-03-14 01:00:00           0         1421       0                 1421
2019-03-14 01:15:00           0         1160       0                 1160
2019-03-14 01:30:00           0          987       0                  987
2019-03-14 01:45:00           0         1422       0                 1422
2019-03-14 02:00:00           0         1352       0                 1352
2019-03-14 02:15:00           0          903       0                  903
2019-03-14 02:30:00           0          974       0                  974
2019-03-14 02:45:00           0         1237       0                 1237
2019-03-14 03:00:00           0          892       0                  892
2019-03-14 03:15:00           0          874       0                  874
2019-03-14 03:30:00           0         1219       0                 1219
2019-03-14 03:45:00           0         1100       0                 1100
2019-03-14 04:00:00           0          853       0                  853
2019-03-14 04:15:00           0          775       0                  775
2019-03-14 04:30:00           0         1108       0                 1108
2019-03-14 04:45:00           0          683       0                  683
2019-03-14 05:00:00           0          895       0                  895
2019-03-14 05:15:00           0         1892       0                 1892
2019-03-14 05:30:00           0         3617       0                 3617
2019-03-14 05:45:00           0         2147       0                 2147
2019-03-14 06:00:00           0         1098       0                 1098
2019-03-14 06:15:00           0          996       0                  996
2019-03-14 06:30:00           1         2066       0                 2065
2019-03-14 06:45:00          67         1126       0                 1059
2019-03-14 07:00:00         130         1544       0                 1414
2019-03-14 07:15:00         354          749       0                  395
2019-03-14 07:30:00         579         1078       0                  499
2019-03-14 07:45:00         700         1016       0                  316
2019-03-14 08:00:00         924          982       0                   58
2019-03-14 08:15:00        1083         1078       5                    0
2019-03-14 08:30:00        1424         1796       0                  372
2019-03-14 08:45:00        1631         1278     353                    0
2019-03-14 09:00:00        1966         1075     891                    0
2019-03-14 09:15:00        2181          772    1409                    0
2019-03-14 09:30:00        2293          722    1571                    0
2019-03-14 09:45:00        2454          563    1891                    0
2019-03-14 10:00:00        2542          611    1931                    0
2019-03-14 10:15:00        2460          784    1676                    0
2019-03-14 10:30:00        2174         2705       0                  531
2019-03-14 10:45:00        2348         1779     569                    0
2019-03-14 11:00:00        2267         1432     835                    0
2019-03-14 11:15:00        2198         1657     541                    0
2019-03-14 11:30:00        2065         1467     598                    0
2019-03-14 11:45:00        1568          752     816                    0
2019-03-14 12:00:00        1572          877     695                    0
2019-03-14 12:15:00        1353          765     588                    0
2019-03-14 12:30:00        1358          845     513                    0
2019-03-14 12:45:00        1341          860     481                    0
2019-03-14 13:00:00        1270          817     453                    0
2019-03-14 13:15:00        1175          738     437                    0
2019-03-14 13:30:00        1105          679     426                    0
2019-03-14 13:45:00        1207          811     396                    0
2019-03-14 14:00:00        1225          827     398                    0
2019-03-14 14:15:00        1121          709     412                    0
2019-03-14 14:30:00        1027          688     339                    0
2019-03-14 14:45:00        1132          818     314                    0
2019-03-14 15:00:00        1161          860     301                    0
2019-03-14 15:15:00        1094          802     292                    0
2019-03-14 15:30:00        1008         1603       0                  595
2019-03-14 15:45:00         868         1091       0                  223
2019-03-14 16:00:00         698          947       0                  249
2019-03-14 16:15:00         492          923       0                  431
2019-03-14 16:30:00         376          822       0                  446
2019-03-14 16:45:00         249          723       0                  474
2019-03-14 17:00:00         147         1553       0                 1406
2019-03-14 17:15:00         101         2005       0                 1904
2019-03-14 17:30:00          58         1675       0                 1617
2019-03-14 17:45:00          26         1679       0                 1653
2019-03-14 18:00:00           2         1555       0                 1553
2019-03-14 18:15:00           0         2453       0                 2453
2019-03-14 18:30:00           0         3079       0                 3079
2019-03-14 18:45:00           0         1772       0                 1772
2019-03-14 19:00:00           0         2943       0                 2943
2019-03-14 19:15:00           0         1999       0                 1999
2019-03-14 19:30:00           0         2224       0                 2224
2019-03-14 19:45:00           0         2778       0                 2778
2019-03-14 20:00:00           0         3024       0                 3024
2019-03-14 20:15:00           0         3021       0                 3021
2019-03-14 20:30:00           0         2604       0                 2604
2019-03-14 20:45:00           0         4046       0                 4046
2019-03-14 21:00:00           0         2689       0                 2689
2019-03-14 21:15:00           0         2857       0                 2857
2019-03-14 21:30:00           0         2820       0                 2820
2019-03-14 21:45:00           0         2096       0                 2096
2019-03-14 22:00:00           0         2373       0                 2373
2019-03-14 22:15:00           0         2160       0                 2160
2019-03-14 22:30:00           0         2074       0                 2074
2019-03-14 22:45:00           0         4348       0                 4348
2019-03-14 23:00:00           0         2792       0                 2792
2019-03-14 23:15:00           0         3449       0                 3449
2019-03-14 23:30:00           0         2367       0                 2367
2019-03-14 23:45:00           0         1857       0                 1857

In [93]:
totalcharge=rawdata['Charge'].sum()/4
totalcharge

4782.75

In [94]:
import datetime

In [95]:
datanotstart=rawdata[rawdata.Generation==0]
dataonlystart=rawdata[rawdata.Generation!=0]
start_time=dataonlystart.index[0]
consumption_night=rawdata.loc[:start_time,'Consumption'].sum()/4

In [96]:
if totalcharge+batt>9600:
    discharge_only_at_night=1
    if batt-consumption_night>0.6*9600:
        batt_start=batt-consumption_night
    else:
        batt_start=0.6*9600
else:
    discharge_only_at_night=0
    batt_start=percent_batt*96

In [97]:
discharge_only_at_night

1

In [98]:
contactor=[]

In [99]:
for i in rawdata[rawdata.index[0]:start_time].drop(start_time).index:
    if discharge_only_at_night==1:
        contactor.append(1)
    else:
        contactor.append(0)

In [100]:
len(contactor)

25

In [101]:
lastchargetime=rawdata[rawdata['Charge']!=0].index[-1]
stop_time=lastchargetime+pd.Timedelta('15 min')

In [102]:

remain=batt_start-9600*0.6
overcharge=batt_start+totalcharge-9600
for i in rawdata[start_time:lastchargetime].index:
    if rawdata.loc[i,'Charge'] > 0:
        contactor.append(1)
        remain += rawdata.loc[i,'Charge']/4
    elif overcharge <= 0:
        contactor.append(0)
    elif remain==0:
        contactor.append(0)
    else:
        contactor.append(1)
        overcharge=overcharge-(rawdata.loc[i,'Consumption']-rawdata.loc[i,'Generation'])/4

In [103]:
for i in rawdata[stop_time:].index:
    contactor.append(0)

In [104]:
len(contactor)

95

In [105]:
rawdata['Contactor']=contactor

In [106]:
rawdata

,Generation,Consumption,Charge,Consumption_afterPV,Contactor
Time,,,,,
2019-03-14 00:15:00,0,1562,0,1562,1
2019-03-14 00:30:00,0,1662,0,1662,1
2019-03-14 00:45:00,0,1623,0,1623,1
2019-03-14 01:00:00,0,1421,0,1421,1
2019-03-14 01:15:00,0,1160,0,1160,1
2019-03-14 01:30:00,0,987,0,987,1
2019-03-14 01:45:00,0,1422,0,1422,1
2019-03-14 02:00:00,0,1352,0,1352,1
2019-03-14 02:15:00,0,903,0,903,1
2019-03-14 02:30:00,0,974,0,974,1
2019-03-14 02:45:00,0,1237,0,1237,1
2019-03-14 03:00:00,0,892,0,892,1
2019-03-14 03:15:00,0,874,0,874,1
2019-03-14 03:30:00,0,1219,0,1219,1
2019-03-14 03:45:00,0,1100,0,1100,1
2019-03-14 04:00:00,0,853,0,853,1
2019-03-14 04:15:00,0,775,0,775,1
2019-03-14 04:30:00,0,1108,0,1108,1
2019-03-14 04:45:00,0,683,0,683,1
2019-03-14 05:00:00,0,895,0,895,1
2019-03-14 05:15:00,0,1892,0,1892,1
2019-03-14 05:30:00,0,3617,0,3617,1
2019-03-14 05:45:00,0,2147,0,2147,1
2019-03-14 06:00:00,0,1098,0,1098,1
2019-03-14 06:15:00,0,996,0,996,1
2019-03-14 06:30:00,1,2066,0,2065,0
2019-03-14 06:45:00,67,1126,0,1059,0
2019-03-14 07:00:00,130,1544,0,1414,0
2019-03-14 07:15:00,354,749,0,395,0
2019-03-14 07:30:00,579,1078,0,499,0
2019-03-14 07:45:00,700,1016,0,316,0
2019-03-14 08:00:00,924,982,0,58,0
2019-03-14 08:15:00,1083,1078,5,0,1
2019-03-14 08:30:00,1424,1796,0,372,1
2019-03-14 08:45:00,1631,1278,353,0,1
2019-03-14 09:00:00,1966,1075,891,0,1
2019-03-14 09:15:00,2181,772,1409,0,1
2019-03-14 09:30:00,2293,722,1571,0,1
2019-03-14 09:45:00,2454,563,1891,0,1
2019-03-14 10:00:00,2542,611,1931,0,1
2019-03-14 10:15:00,2460,784,1676,0,1
2019-03-14 10:30:00,2174,2705,0,531,1
2019-03-14 10:45:00,2348,1779,569,0,1
2019-03-14 11:00:00,2267,1432,835,0,1
2019-03-14 11:15:00,2198,1657,541,0,1
2019-03-14 11:30:00,2065,1467,598,0,1
2019-03-14 11:45:00,1568,752,816,0,1
2019-03-14 12:00:00,1572,877,695,0,1
2019-03-14 12:15:00,1353,765,588,0,1
2019-03-14 12:30:00,1358,845,513,0,1
2019-03-14 12:45:00,1341,860,481,0,1
2019-03-14 13:00:00,1270,817,453,0,1
2019-03-14 13:15:00,1175,738,437,0,1
2019-03-14 13:30:00,1105,679,426,0,1
2019-03-14 13:45:00,1207,811,396,0,1
2019-03-14 14:00:00,1225,827,398,0,1
2019-03-14 14:15:00,1121,709,412,0,1
2019-03-14 14:30:00,1027,688,339,0,1
2019-03-14 14:45:00,1132,818,314,0,1
2019-03-14 15:00:00,1161,860,301,0,1
2019-03-14 15:15:00,1094,802,292,0,1
2019-03-14 15:30:00,1008,1603,0,595,0
2019-03-14 15:45:00,868,1091,0,223,0
2019-03-14 16:00:00,698,947,0,249,0
2019-03-14 16:15:00,492,923,0,431,0
2019-03-14 16:30:00,376,822,0,446,0
2019-03-14 16:45:00,249,723,0,474,0
2019-03-14 17:00:00,147,1553,0,1406,0
2019-03-14 17:15:00,101,2005,0,1904,0
2019-03-14 17:30:00,58,1675,0,1617,0
2019-03-14 17:45:00,26,1679,0,1653,0
2019-03-14 18:00:00,2,1555,0,1553,0
2019-03-14 18:15:00,0,2453,0,2453,0
2019-03-14 18:30:00,0,3079,0,3079,0
2019-03-14 18:45:00,0,1772,0,1772,0
2019-03-14 19:00:00,0,2943,0,2943,0
2019-03-14 19:15:00,0,1999,0,1999,0
2019-03-14 19:30:00,0,2224,0,2224,0
2019-03-14 19:45:00,0,2778,0,2778,0
2019-03-14 20:00:00,0,3024,0,3024,0
2019-03-14 20:15:00,0,3021,0,3021,0
2019-03-14 20:30:00,0,2604,0,2604,0
2019-03-14 20:45:00,0,4046,0,4046,0
2019-03-14 21:00:00,0,2689,0,2689,0
2019-03-14 21:15:00,0,2857,0,2857,0
2019-03-14 21:30:00,0,2820,0,2820,0
2019-03-14 21:45:00,0,2096,0,2096,0
2019-03-14 22:00:00,0,2373,0,2373,0
2019-03-14 22:15:00,0,2160,0,2160,0
2019-03-14 22:30:00,0,2074,0,2074,0
2019-03-14 22:45:00,0,4348,0,4348,0
2019-03-14 23:00:00,0,2792,0,2792,0
2019-03-14 23:15:00,0,3449,0,3449,0
2019-03-14 23:30:00,0,2367,0,2367,0
2019-03-14 23:45:00,0,1857,0,1857,0

In [107]:
battleft=(percent_batt-60)*96*4
rawdata['Discharge']=rawdata['Contactor']*0
for i in rawdata.index:
    if rawdata.loc[i,'Contactor']==1:
        if rawdata.loc[i,'Charge'] != 0:
            battleft=battleft+rawdata.loc[i,'Charge']
        else:
            if battleft >= rawdata.loc[i,'Consumption_afterPV']:
                rawdata.loc[i,'Discharge']= rawdata.loc[i,'Consumption_afterPV']
                battleft=battleft- rawdata.loc[i,'Consumption_afterPV']
            else:
                rawdata.loc[i,'Discharge']=battleft
                battleft=0

In [108]:
rawdata

,Generation,Consumption,Charge,Consumption_afterPV,Contactor,Discharge
Time,,,,,,
2019-03-14 00:15:00,0,1562,0,1562,1,1562
2019-03-14 00:30:00,0,1662,0,1662,1,1662
2019-03-14 00:45:00,0,1623,0,1623,1,1623
2019-03-14 01:00:00,0,1421,0,1421,1,1421
2019-03-14 01:15:00,0,1160,0,1160,1,1160
2019-03-14 01:30:00,0,987,0,987,1,987
2019-03-14 01:45:00,0,1422,0,1422,1,1422
2019-03-14 02:00:00,0,1352,0,1352,1,1352
2019-03-14 02:15:00,0,903,0,903,1,903
2019-03-14 02:30:00,0,974,0,974,1,974
2019-03-14 02:45:00,0,1237,0,1237,1,1237
2019-03-14 03:00:00,0,892,0,892,1,892
2019-03-14 03:15:00,0,874,0,874,1,165
2019-03-14 03:30:00,0,1219,0,1219,1,0
2019-03-14 03:45:00,0,1100,0,1100,1,0
2019-03-14 04:00:00,0,853,0,853,1,0
2019-03-14 04:15:00,0,775,0,775,1,0
2019-03-14 04:30:00,0,1108,0,1108,1,0
2019-03-14 04:45:00,0,683,0,683,1,0
2019-03-14 05:00:00,0,895,0,895,1,0
2019-03-14 05:15:00,0,1892,0,1892,1,0
2019-03-14 05:30:00,0,3617,0,3617,1,0
2019-03-14 05:45:00,0,2147,0,2147,1,0
2019-03-14 06:00:00,0,1098,0,1098,1,0
2019-03-14 06:15:00,0,996,0,996,1,0
2019-03-14 06:30:00,1,2066,0,2065,0,0
2019-03-14 06:45:00,67,1126,0,1059,0,0
2019-03-14 07:00:00,130,1544,0,1414,0,0
2019-03-14 07:15:00,354,749,0,395,0,0
2019-03-14 07:30:00,579,1078,0,499,0,0
2019-03-14 07:45:00,700,1016,0,316,0,0
2019-03-14 08:00:00,924,982,0,58,0,0
2019-03-14 08:15:00,1083,1078,5,0,1,0
2019-03-14 08:30:00,1424,1796,0,372,1,5
2019-03-14 08:45:00,1631,1278,353,0,1,0
2019-03-14 09:00:00,1966,1075,891,0,1,0
2019-03-14 09:15:00,2181,772,1409,0,1,0
2019-03-14 09:30:00,2293,722,1571,0,1,0
2019-03-14 09:45:00,2454,563,1891,0,1,0
2019-03-14 10:00:00,2542,611,1931,0,1,0
2019-03-14 10:15:00,2460,784,1676,0,1,0
2019-03-14 10:30:00,2174,2705,0,531,1,531
2019-03-14 10:45:00,2348,1779,569,0,1,0
2019-03-14 11:00:00,2267,1432,835,0,1,0
2019-03-14 11:15:00,2198,1657,541,0,1,0
2019-03-14 11:30:00,2065,1467,598,0,1,0
2019-03-14 11:45:00,1568,752,816,0,1,0
2019-03-14 12:00:00,1572,877,695,0,1,0
2019-03-14 12:15:00,1353,765,588,0,1,0
2019-03-14 12:30:00,1358,845,513,0,1,0
2019-03-14 12:45:00,1341,860,481,0,1,0
2019-03-14 13:00:00,1270,817,453,0,1,0
2019-03-14 13:15:00,1175,738,437,0,1,0
2019-03-14 13:30:00,1105,679,426,0,1,0
2019-03-14 13:45:00,1207,811,396,0,1,0
2019-03-14 14:00:00,1225,827,398,0,1,0
2019-03-14 14:15:00,1121,709,412,0,1,0
2019-03-14 14:30:00,1027,688,339,0,1,0
2019-03-14 14:45:00,1132,818,314,0,1,0
2019-03-14 15:00:00,1161,860,301,0,1,0
2019-03-14 15:15:00,1094,802,292,0,1,0
2019-03-14 15:30:00,1008,1603,0,595,0,0
2019-03-14 15:45:00,868,1091,0,223,0,0
2019-03-14 16:00:00,698,947,0,249,0,0
2019-03-14 16:15:00,492,923,0,431,0,0
2019-03-14 16:30:00,376,822,0,446,0,0
2019-03-14 16:45:00,249,723,0,474,0,0
2019-03-14 17:00:00,147,1553,0,1406,0,0
2019-03-14 17:15:00,101,2005,0,1904,0,0
2019-03-14 17:30:00,58,1675,0,1617,0,0
2019-03-14 17:45:00,26,1679,0,1653,0,0
2019-03-14 18:00:00,2,1555,0,1553,0,0
2019-03-14 18:15:00,0,2453,0,2453,0,0
2019-03-14 18:30:00,0,3079,0,3079,0,0
2019-03-14 18:45:00,0,1772,0,1772,0,0
2019-03-14 19:00:00,0,2943,0,2943,0,0
2019-03-14 19:15:00,0,1999,0,1999,0,0
2019-03-14 19:30:00,0,2224,0,2224,0,0
2019-03-14 19:45:00,0,2778,0,2778,0,0
2019-03-14 20:00:00,0,3024,0,3024,0,0
2019-03-14 20:15:00,0,3021,0,3021,0,0
2019-03-14 20:30:00,0,2604,0,2604,0,0
2019-03-14 20:45:00,0,4046,0,4046,0,0
2019-03-14 21:00:00,0,2689,0,2689,0,0
2019-03-14 21:15:00,0,2857,0,2857,0,0
2019-03-14 21:30:00,0,2820,0,2820,0,0
2019-03-14 21:45:00,0,2096,0,2096,0,0
2019-03-14 22:00:00,0,2373,0,2373,0,0
2019-03-14 22:15:00,0,2160,0,2160,0,0
2019-03-14 22:30:00,0,2074,0,2074,0,0
2019-03-14 22:45:00,0,4348,0,4348,0,0
2019-03-14 23:00:00,0,2792,0,2792,0,0
2019-03-14 23:15:00,0,3449,0,3449,0,0
2019-03-14 23:30:00,0,2367,0,2367,0,0
2019-03-14 23:45:00,0,1857,0,1857,0,0

In [117]:
checkcharge=(percent_batt-60)*96*4
cclist=[]
for i in rawdata.index:
    if rawdata.loc[i,'Contactor']==1:
        if rawdata.loc[i,'Charge'] != 0 :
            if checkcharge+rawdata.loc[i,'Charge']>=40*96*4:
                rawdata.loc[i,'Charge']=40*96*4-checkcharge
                checkcharge=40*96*4
                cclist.append(checkcharge)
            else:
                checkcharge+=rawdata.loc[i,'Charge']
                cclist.append(checkcharge)
        elif rawdata.loc[i,'Discharge'] != 0:
            if checkcharge-rawdata.loc[i,'Discharge']<=0:
                rawdata.loc[i,'Discharge']=checkcharge
                checkcharge=0
                cclist.append(checkcharge)
            else:    
                checkcharge = checkcharge - rawdata.loc[i,'Discharge']
                cclist.append(checkcharge)
        else:
            cclist.append(checkcharge)
    else:
        cclist.append(checkcharge)
rawdata['Batt_above60%']=cclist

In [118]:
rawdata

,Generation,Consumption,Charge,Consumption_afterPV,Contactor,Discharge,CClist,Batt_above60%
Time,,,,,,,,
2019-03-14 00:15:00,0,1562,0,1562,1,1562,13798,13798
2019-03-14 00:30:00,0,1662,0,1662,1,1662,12136,12136
2019-03-14 00:45:00,0,1623,0,1623,1,1623,10513,10513
2019-03-14 01:00:00,0,1421,0,1421,1,1421,9092,9092
2019-03-14 01:15:00,0,1160,0,1160,1,1160,7932,7932
2019-03-14 01:30:00,0,987,0,987,1,987,6945,6945
2019-03-14 01:45:00,0,1422,0,1422,1,1422,5523,5523
2019-03-14 02:00:00,0,1352,0,1352,1,1352,4171,4171
2019-03-14 02:15:00,0,903,0,903,1,903,3268,3268
2019-03-14 02:30:00,0,974,0,974,1,974,2294,2294
2019-03-14 02:45:00,0,1237,0,1237,1,1237,1057,1057
2019-03-14 03:00:00,0,892,0,892,1,892,165,165
2019-03-14 03:15:00,0,874,0,874,1,165,0,0
2019-03-14 03:30:00,0,1219,0,1219,1,0,0,0
2019-03-14 03:45:00,0,1100,0,1100,1,0,0,0
2019-03-14 04:00:00,0,853,0,853,1,0,0,0
2019-03-14 04:15:00,0,775,0,775,1,0,0,0
2019-03-14 04:30:00,0,1108,0,1108,1,0,0,0
2019-03-14 04:45:00,0,683,0,683,1,0,0,0
2019-03-14 05:00:00,0,895,0,895,1,0,0,0
2019-03-14 05:15:00,0,1892,0,1892,1,0,0,0
2019-03-14 05:30:00,0,3617,0,3617,1,0,0,0
2019-03-14 05:45:00,0,2147,0,2147,1,0,0,0
2019-03-14 06:00:00,0,1098,0,1098,1,0,0,0
2019-03-14 06:15:00,0,996,0,996,1,0,0,0
2019-03-14 06:30:00,1,2066,0,2065,0,0,0,0
2019-03-14 06:45:00,67,1126,0,1059,0,0,0,0
2019-03-14 07:00:00,130,1544,0,1414,0,0,0,0
2019-03-14 07:15:00,354,749,0,395,0,0,0,0
2019-03-14 07:30:00,579,1078,0,499,0,0,0,0
2019-03-14 07:45:00,700,1016,0,316,0,0,0,0
2019-03-14 08:00:00,924,982,0,58,0,0,0,0
2019-03-14 08:15:00,1083,1078,5,0,1,0,5,5
2019-03-14 08:30:00,1424,1796,0,372,1,5,0,0
2019-03-14 08:45:00,1631,1278,353,0,1,0,353,353
2019-03-14 09:00:00,1966,1075,891,0,1,0,1244,1244
2019-03-14 09:15:00,2181,772,1409,0,1,0,2653,2653
2019-03-14 09:30:00,2293,722,1571,0,1,0,4224,4224
2019-03-14 09:45:00,2454,563,1891,0,1,0,6115,6115
2019-03-14 10:00:00,2542,611,1931,0,1,0,8046,8046
2019-03-14 10:15:00,2460,784,1676,0,1,0,9722,9722
2019-03-14 10:30:00,2174,2705,0,531,1,531,9191,9191
2019-03-14 10:45:00,2348,1779,569,0,1,0,9760,9760
2019-03-14 11:00:00,2267,1432,835,0,1,0,10595,10595
2019-03-14 11:15:00,2198,1657,541,0,1,0,11136,11136
2019-03-14 11:30:00,2065,1467,598,0,1,0,11734,11734
2019-03-14 11:45:00,1568,752,816,0,1,0,12550,12550
2019-03-14 12:00:00,1572,877,695,0,1,0,13245,13245
2019-03-14 12:15:00,1353,765,588,0,1,0,13833,13833
2019-03-14 12:30:00,1358,845,513,0,1,0,14346,14346
2019-03-14 12:45:00,1341,860,481,0,1,0,14827,14827
2019-03-14 13:00:00,1270,817,453,0,1,0,15280,15280
2019-03-14 13:15:00,1175,738,80,0,1,0,15360,15360
2019-03-14 13:30:00,1105,679,0,0,1,0,15360,15360
2019-03-14 13:45:00,1207,811,0,0,1,0,15360,15360
2019-03-14 14:00:00,1225,827,0,0,1,0,15360,15360
2019-03-14 14:15:00,1121,709,0,0,1,0,15360,15360
2019-03-14 14:30:00,1027,688,0,0,1,0,15360,15360
2019-03-14 14:45:00,1132,818,0,0,1,0,15360,15360
2019-03-14 15:00:00,1161,860,0,0,1,0,15360,15360
2019-03-14 15:15:00,1094,802,0,0,1,0,15360,15360
2019-03-14 15:30:00,1008,1603,0,595,0,0,15360,15360
2019-03-14 15:45:00,868,1091,0,223,0,0,15360,15360
2019-03-14 16:00:00,698,947,0,249,0,0,15360,15360
2019-03-14 16:15:00,492,923,0,431,0,0,15360,15360
2019-03-14 16:30:00,376,822,0,446,0,0,15360,15360
2019-03-14 16:45:00,249,723,0,474,0,0,15360,15360
2019-03-14 17:00:00,147,1553,0,1406,0,0,15360,15360
2019-03-14 17:15:00,101,2005,0,1904,0,0,15360,15360
2019-03-14 17:30:00,58,1675,0,1617,0,0,15360,15360
2019-03-14 17:45:00,26,1679,0,1653,0,0,15360,15360
2019-03-14 18:00:00,2,1555,0,1553,0,0,15360,15360
2019-03-14 18:15:00,0,2453,0,2453,0,0,15360,15360
2019-03-14 18:30:00,0,3079,0,3079,0,0,15360,15360
2019-03-14 18:45:00,0,1772,0,1772,0,0,15360,15360
2019-03-14 19:00:00,0,2943,0,2943,0,0,15360,15360
2019-03-14 19:15:00,0,1999,0,1999,0,0,15360,15360
2019-03-14 19:30:00,0,2224,0,2224,0,0,15360,15360
2019-03-14 19:45:00,0,2778,0,2778,0,0,15360,15360
2019-03-14 20:00:00,0,3024,0,3024,0,0,15360,15360
2019-03-14 20:15:00,0,3021,0,3021,0,0,15360,15360
2019-03-14 20:30:00,0,2604,0,2604,0,0,15360,15360
2019-03-14 20:45:00,0,4046,0,4046,0,0,15360,15360
2019-03-14 21:00:00,0,2689,0,2689,0,0,15360,15360
2019-03-14 21:15:00,0,2857,0,2857,0,0,15360,15360
2019-03-14 21:30:00,0,2820,0,2820,0,0,15360,15360
2019-03-14 21:45:00,0,2096,0,2096,0,0,15360,15360
2019-03-14 22:00:00,0,2373,0,2373,0,0,15360,15360
2019-03-14 22:15:00,0,2160,0,2160,0,0,15360,15360
2019-03-14 22:30:00,0,2074,0,2074,0,0,15360,15360
2019-03-14 22:45:00,0,4348,0,4348,0,0,15360,15360
2019-03-14 23:00:00,0,2792,0,2792,0,0,15360,15360
2019-03-14 23:15:00,0,3449,0,3449,0,0,15360,15360
2019-03-14 23:30:00,0,2367,0,2367,0,0,15360,15360
2019-03-14 23:45:00,0,1857,0,1857,0,0,15360,15360

In [ ]:
totaldischarge=rawdata['Discharge'].sum()/4
totaldischarge/96

In [ ]:
(rawdata.Charge.sum()-rawdata.Discharge.sum())/4/96

In [ ]:
newpercent_batt=percent_batt+(rawdata.Charge.sum()-rawdata.Discharge.sum())/4/96
newpercent_batt

In [ ]:
%config InlineBackend.figure_format='retina'

In [ ]:
rawdata.plot(kind='line')

In [ ]:
rawdata['Contactor'].plot(kind='line')