In [55]:
from statsmodels.tsa.api import ExponentialSmoothing, SimpleExpSmoothing, Holt
import pandas as pd

## Predict_date is one of input

In [56]:
predict_date='2018_12_13'

## find 15 previous days and num_day<28

In [57]:
num_day=15

In [58]:
predict_day=int(predict_date[8:])
predict_month=int(predict_date[5:7])
predict_year=int(predict_date[0:4])

In [59]:
str(predict_year)+'_'+str(predict_month)+'_'+str(predict_day)

'2018_12_13'

In [60]:
daybefore=[]
pmb=predict_month-1
dayleft=num_day-predict_day

In [62]:
if predict_day>=num_day:
    day=1
    while day<=predict_day:
        daybefore.append(str(predict_year)+'_'+str(predict_month)+'_'+str(day).zfill(2))
        day+=1
else:
    if pmb==1 or pmb==3 or pmb==5 or pmb==7 or pmb==8 or pmb==10 or pmb==12:
        for i in range(31-dayleft,31,1):
            daybefore.append(str(predict_year)+'_'+str(pmb)+'_'+str(i).zfill(2))
        for i in range(1,predict_day,1):
            daybefore.append(str(predict_year)+'_'+str(predict_month)+'_'+str(i).zfill(2))
    elif pmb==4 or pmb==6 or pmb==9 or pmb==11:
        for i in range(30-dayleft,30,1):
            daybefore.append(str(predict_year)+'_'+str(pmb)+'_'+str(i).zfill(2))
        for i in range(1,predict_day,1):
            daybefore.append(str(predict_year)+'_'+str(predict_month)+'_'+str(i).zfill(2))
    else:
        if predict_year%4==0:
            for i in range(29-dayleft,29,1):
                daybefore.append(str(predict_year)+'_'+str(pmb)+'_'+str(i).zfill(2))
            for i in range(1,predict_day,1):
                daybefore.append(str(predict_year)+'_'+str(predict_month)+'_'+str(i).zfill(2))
        else:
            for i in range(28-dayleft,28,1):
                daybefore.append(str(predict_year)+'_'+str(pmb)+'_'+str(i).zfill(2))
            for i in range(1,predict_day,1):
                daybefore.append(str(predict_year)+'_'+str(predict_month)+'_'+str(i).zfill(2))

In [63]:
daybefore

['2018_11_28',
 '2018_11_29',
 '2018_12_01',
 '2018_12_02',
 '2018_12_03',
 '2018_12_04',
 '2018_12_05',
 '2018_12_06',
 '2018_12_07',
 '2018_12_08',
 '2018_12_09',
 '2018_12_10',
 '2018_12_11',
 '2018_12_12']

## Have daybefore

In [64]:
pathlist=[]
for i in daybefore:
    pathlist.append('Energy_Balance_'+str(i))
pathlist

['Energy_Balance_2018_11_28',
 'Energy_Balance_2018_11_29',
 'Energy_Balance_2018_12_01',
 'Energy_Balance_2018_12_02',
 'Energy_Balance_2018_12_03',
 'Energy_Balance_2018_12_04',
 'Energy_Balance_2018_12_05',
 'Energy_Balance_2018_12_06',
 'Energy_Balance_2018_12_07',
 'Energy_Balance_2018_12_08',
 'Energy_Balance_2018_12_09',
 'Energy_Balance_2018_12_10',
 'Energy_Balance_2018_12_11',
 'Energy_Balance_2018_12_12']

In [65]:
def clean(path):
    rawdata=pd.read_csv(path+".csv", delimiter=";" )
    rawdata.rename(columns={' ':'Time'},inplace=True)
    rawdata['Time']=rawdata['Time'].str.replace('[^\d\:]','')
    rawdata['Time']=pd.to_datetime(rawdata.Time)
    rawdata.set_index('Time', inplace=True)
    rawdata.drop(['Total consumption / Mean values [W] ',
           'Grid feed-in / Mean values [W] ',
           'Direct consumption / Mean values [W]  ',
           'Battery charging / Mean values [W]  ',
           'Target value / Mean values [W]  ', 'Output value / Mean values [W]  '],axis=1,inplace=True)
    rawdata.loc[rawdata.loc[pd.IndexSlice[:,'Battery discharging / Mean values [W] ']]==' ']
    deleteindex=rawdata.loc[rawdata.loc[pd.IndexSlice[:,'Battery discharging / Mean values [W] ']]==' '].index
    rawdata.drop(deleteindex,inplace=True)
    for i in rawdata.columns:
        rawdata[i].fillna('0',inplace=True)
        rawdata[i]=rawdata[i].apply(lambda x: x.replace(' ', '0'))
        rawdata[i]=rawdata[i].str.replace('\D','').astype(int)
    rawdata['Consumption']=rawdata['Direct consumption / Mean values [W] ']+rawdata['Battery discharging / Mean values [W] ']+rawdata['External energy supply / Mean values [W] ']
    rawdata.rename(columns={'PV power generation / Mean values [W]  ':'Generation'},inplace=True)
    rawdata.drop(['Direct consumption / Mean values [W] ', 'Battery discharging / Mean values [W] ','External energy supply / Mean values [W] '],axis=1,inplace=True)
    rawdata.drop(['Generation'],axis=1,inplace=True)
    return rawdata

In [66]:
data=[]

In [67]:
for i in pathlist:
    df=clean(i)
    data.append(df)
data

[                     Consumption
 Time
 2019-02-21 00:15:00         2291
 2019-02-21 00:30:00         1129
 2019-02-21 00:45:00         1126
 2019-02-21 01:00:00         1631
 2019-02-21 01:15:00         1084
 2019-02-21 01:30:00         1148
 2019-02-21 01:45:00         1214
 2019-02-21 02:00:00         1040
 2019-02-21 02:15:00         1577
 2019-02-21 02:30:00         1007
 2019-02-21 02:45:00         1020
 2019-02-21 03:00:00         1001
 2019-02-21 03:15:00         1031
 2019-02-21 03:30:00          950
 2019-02-21 03:45:00         1011
 2019-02-21 04:00:00          921
 2019-02-21 04:15:00          748
 2019-02-21 04:30:00         1410
 2019-02-21 04:45:00          985
 2019-02-21 05:00:00         2302
 2019-02-21 05:15:00         2171
 2019-02-21 05:30:00         2230
 2019-02-21 05:45:00         2110
 2019-02-21 06:00:00         1312
 2019-02-21 06:15:00         1290
 2019-02-21 06:30:00         2154
 2019-02-21 06:45:00          906
 2019-02-21 07:00:00          968
 2019-02-21 07:15:00         1122
 2019-02-21 07:30:00         1003
 ...                          ...
 2019-02-21 16:30:00          920
 2019-02-21 16:45:00          785
 2019-02-21 17:00:00         1529
 2019-02-21 17:15:00         1434
 2019-02-21 17:30:00         1484
 2019-02-21 17:45:00         1330
 2019-02-21 18:00:00         1468
 2019-02-21 18:15:00         2714
 2019-02-21 18:30:00         1442
 2019-02-21 18:45:00         1701
 2019-02-21 19:00:00         1625
 2019-02-21 19:15:00         1868
 2019-02-21 19:30:00         2655
 2019-02-21 19:45:00         2859
 2019-02-21 20:00:00         3800
 2019-02-21 20:15:00         2909
 2019-02-21 20:30:00         2296
 2019-02-21 20:45:00         1995
 2019-02-21 21:00:00         1966
 2019-02-21 21:15:00         2157
 2019-02-21 21:30:00         1670
 2019-02-21 21:45:00         1828
 2019-02-21 22:00:00         1980
 2019-02-21 22:15:00         1804
 2019-02-21 22:30:00         1714
 2019-02-21 22:45:00         1680
 2019-02-21 23:00:00         1611
 2019-02-21 23:15:00         1739
 2019-02-21 23:30:00         1469
 2019-02-21 23:45:00         4176

 [95 rows x 1 columns],                      Consumption
 Time
 2019-02-21 00:15:00         1583
 2019-02-21 00:30:00         2062
 2019-02-21 00:45:00         1420
 2019-02-21 01:00:00         1483
 2019-02-21 01:15:00         1494
 2019-02-21 01:30:00         1278
 2019-02-21 01:45:00         1297
 2019-02-21 02:00:00         1067
 2019-02-21 02:15:00         1188
 2019-02-21 02:30:00         1071
 2019-02-21 02:45:00         1141
 2019-02-21 03:00:00         1176
 2019-02-21 03:15:00          925
 2019-02-21 03:30:00         1039
 2019-02-21 03:45:00         1340
 2019-02-21 04:00:00          975
 2019-02-21 04:15:00          931
 2019-02-21 04:30:00          927
 2019-02-21 04:45:00          987
 2019-02-21 05:00:00         1067
 2019-02-21 05:15:00         3088
 2019-02-21 05:30:00         1954
 2019-02-21 05:45:00         1182
 2019-02-21 06:00:00         1189
 2019-02-21 06:15:00         1172
 2019-02-21 06:30:00         1972
 2019-02-21 06:45:00         1103
 2019-02-21 07:00:00          923
 2019-02-21 07:15:00         1238
 2019-02-21 07:30:00          902
 ...                          ...
 2019-02-21 16:30:00         1501
 2019-02-21 16:45:00         1453
 2019-02-21 17:00:00         1661
 2019-02-21 17:15:00         2629
 2019-02-21 17:30:00         2432
 2019-02-21 17:45:00         1948
 2019-02-21 18:00:00         1707
 2019-02-21 18:15:00         2634
 2019-02-21 18:30:00         3097
 2019-02-21 18:45:00         2687
 2019-02-21 19:00:00         1769
 2019-02-21 19:15:00         3056
 2019-02-21 19:30:00         4171
 2019-02-21 19:45:00         3633
 2019-02-21 20:00:00         2745
 2019-02-21 20:15:00         2811
 2019-02-21 20:30:00         2732
 2019-02-21 20:45:00         3510
 2019-02-21 21:00:00         3282
 2019-02-21 21:15:00         2926
 2019-02-21 21:30:00         2250
 2019-02-21 21:45:00         2457
 2019-02-21 22:00:00         2083
 2019-02-21 22:15:00         2118
 2019-02-21 22:30:00         2337
 2019-02-21 22:45:00         2223
 2019-02-21 23:00:00         4243
 2019-02-21 23:15:00         3135
 2019-02-21 23:30:00         3074
 2019-02-21 23:45:00         2890

 [95 rows x 1 columns],                      Consumption
 Time
 2019-02-21 00:15:00         1874
 2019-02-21 00:30:00         3255
 2019-02-21 00:45:00         2560
 2019-02-21 01:00:00         2862
 2019-02-21 01:15:00         3002
 2019-02-21 01:30:00         2171
 2019-02-21 01:45:00         1925
 2019-02-21 02:00:00         1561
 2019-02-21 02:15:00         2021
 2019-02-21 02:30:00         1997
 2019-02-21 02:45:00         1804
 2019-02-21 03:00:00         1735
 2019-02-21 03:15:00         1933
 2019-02-21 03:30:00         1657
 2019-02-21 03:45:00         1457
 2019-02-21 04:00:00         1361
 2019-02-21 04:15:00         1370
 2019-02-21 04:30:00         1003
 2019-02-21 04:45:00         1440
 2019-02-21 05:00:00         1766
 2019-02-21 05:15:00         1323
 2019-02-21 05:30:00         3197
 2019-02-21 05:45:00         1771
 2019-02-21 06:00:00         1591
 2019-02-21 06:15:00         1598
 2019-02-21 06:30:00         2425
 2019-02-21 06:45:00         1569
 2019-02-21 07:00:00         1551
 2019-02-21 07:15:00         1164
 2019-02-21 07:30:00         1735
 ...                          ...
 2019-02-21 16:30:00         1678
 2019-02-21 16:45:00         2132
 2019-02-21 17:00:00         2427
 2019-02-21 17:15:00         2909
 2019-02-21 17:30:00         2525
 2019-02-21 17:45:00         3689
 2019-02-21 18:00:00         2534
 2019-02-21 18:15:00         2478
 2019-02-21 18:30:00         3110
 2019-02-21 18:45:00         4005
 2019-02-21 19:00:00         3409
 2019-02-21 19:15:00         3537
 2019-02-21 19:30:00         2984
 2019-02-21 19:45:00         3024
 2019-02-21 20:00:00         3049
 2019-02-21 20:15:00         4645
 2019-02-21 20:30:00         3269
 2019-02-21 20:45:00         3558
 2019-02-21 21:00:00         5191
 2019-02-21 21:15:00         3714
 2019-02-21 21:30:00         2978
 2019-02-21 21:45:00         3411
 2019-02-21 22:00:00         2800
 2019-02-21 22:15:00         2622
 2019-02-21 22:30:00         2514
 2019-02-21 22:45:00         3262
 2019-02-21 23:00:00         1972
 2019-02-21 23:15:00         2810
 2019-02-21 23:30:00         1988
 2019-02-21 23:45:00         2388

 [95 rows x 1 columns],                      Consumption
 Time
 2019-02-21 00:15:00         2275
 2019-02-21 00:30:00         2570
 2019-02-21 00:45:00         2214
 2019-02-21 01:00:00         1927
 2019-02-21 01:15:00         1952
 2019-02-21 01:30:00         1791
 2019-02-21 01:45:00         2051
 2019-02-21 02:00:00         2022
 2019-02-21 02:15:00         1893
 2019-02-21 02:30:00         1641
 2019-02-21 02:45:00         1727
 2019-02-21 03:00:00         1448
 2019-02-21 03:15:00         1696
 2019-02-21 03:30:00         1699
 2019-02-21 03:45:00         1573
 2019-02-21 04:00:00         1661
 2019-02-21 04:15:00         1619
 2019-02-21 04:30:00         1558
 2019-02-21 04:45:00         1411
 2019-02-21 05:00:00         2040
 2019-02-21 05:15:00         2588
 2019-02-21 05:30:00         2852
 2019-02-21 05:45:00         2122
 2019-02-21 06:00:00         1970
 2019-02-21 06:15:00         1819
 2019-02-21 06:30:00         2011
 2019-02-21 06:45:00         1222
 2019-02-21 07:00:00         1026
 2019-02-21 07:15:00          885
 2019-02-21 07:30:00         1004
 ...                          ...
 2019-02-21 16:30:00          833
 2019-02-21 16:45:00          927
 2019-02-21 17:00:00         2017
 2019-02-21 17:15:00         3239
 2019-02-21 17:30:00         3441
 2019-02-21 17:45:00         3448
 2019-02-21 18:00:00         3269
 2019-02-21 18:15:00         2362
 2019-02-21 18:30:00         4256
 2019-02-21 18:45:00         3802
 2019-02-21 19:00:00         4498
 2019-02-21 19:15:00         3935
 2019-02-21 19:30:00         4110
 2019-02-21 19:45:00         4270
 2019-02-21 20:00:00         4064
 2019-02-21 20:15:00         4879
 2019-02-21 20:30:00         3651
 2019-02-21 20:45:00         2752
 2019-02-21 21:00:00         3140
 2019-02-21 21:15:00         2985
 2019-02-21 21:30:00         2605
 2019-02-21 21:45:00         2324
 2019-02-21 22:00:00         2931
 2019-02-21 22:15:00         2419
 2019-02-21 22:30:00         3297
 2019-02-21 22:45:00         2506
 2019-02-21 23:00:00         2573
 2019-02-21 23:15:00         2419
 2019-02-21 23:30:00         2187
 2019-02-21 23:45:00         2384

 [95 rows x 1 columns],                      Consumption
 Time
 2019-02-21 00:15:00         2550
 2019-02-21 00:30:00         2011
 2019-02-21 00:45:00         2442
 2019-02-21 01:00:00         2272
 2019-02-21 01:15:00         2121
 2019-02-21 01:30:00         1918
 2019-02-21 01:45:00         1889
 2019-02-21 02:00:00         1962
 2019-02-21 02:15:00         1809
 2019-02-21 02:30:00         1549
 2019-02-21 02:45:00         1712
 2019-02-21 03:00:00         1665
 2019-02-21 03:15:00         1655
 2019-02-21 03:30:00         1563
 2019-02-21 03:45:00         1604
 2019-02-21 04:00:00         1719
 2019-02-21 04:15:00         1406
 2019-02-21 04:30:00         1593
 2019-02-21 04:45:00         1713
 2019-02-21 05:00:00         3525
 2019-02-21 05:15:00         2015
 2019-02-21 05:30:00         2714
 2019-02-21 05:45:00         1430
 2019-02-21 06:00:00         1060
 2019-02-21 06:15:00         1410
 2019-02-21 06:30:00         1192
 2019-02-21 06:45:00         1000
 2019-02-21 07:00:00          918
 2019-02-21 07:15:00          988
 2019-02-21 07:30:00          927
 ...                          ...
 2019-02-21 16:30:00          918
 2019-02-21 16:45:00          830
 2019-02-21 17:00:00          656
 2019-02-21 17:15:00         2177
 2019-02-21 17:30:00         2115
 2019-02-21 17:45:00         3404
 2019-02-21 18:00:00         2879
 2019-02-21 18:15:00         2612
 2019-02-21 18:30:00         2343
 2019-02-21 18:45:00         2255
 2019-02-21 19:00:00         2288
 2019-02-21 19:15:00         2063
 2019-02-21 19:30:00         2074
 2019-02-21 19:45:00         2164
 2019-02-21 20:00:00         3150
 2019-02-21 20:15:00         4944
 2019-02-21 20:30:00         3453
 2019-02-21 20:45:00         3325
 2019-02-21 21:00:00         3173
 2019-02-21 21:15:00         2639
 2019-02-21 21:30:00         2663
 2019-02-21 21:45:00         2975
 2019-02-21 22:00:00         3675
 2019-02-21 22:15:00         3630
 2019-02-21 22:30:00         3379
 2019-02-21 22:45:00         3860
 2019-02-21 23:00:00         3681
 2019-02-21 23:15:00         3185
 2019-02-21 23:30:00         3197
 2019-02-21 23:45:00         3229

 [95 rows x 1 columns],                      Consumption
 Time
 2019-02-21 00:15:00         3066
 2019-02-21 00:30:00         2806
 2019-02-21 00:45:00         2686
 2019-02-21 01:00:00         2487
 2019-02-21 01:15:00         2243
 2019-02-21 01:30:00         2440
 2019-02-21 01:45:00         1897
 2019-02-21 02:00:00         2407
 2019-02-21 02:15:00         1939
 2019-02-21 02:30:00         2279
 2019-02-21 02:45:00         2018
 2019-02-21 03:00:00         1979
 2019-02-21 03:15:00         1806
 2019-02-21 03:30:00         1711
 2019-02-21 03:45:00         1980
 2019-02-21 04:00:00         1895
 2019-02-21 04:15:00         1744
 2019-02-21 04:30:00         1591
 2019-02-21 04:45:00         1536
 2019-02-21 05:00:00         2179
 2019-02-21 05:15:00         2541
 2019-02-21 05:30:00         2547
 2019-02-21 05:45:00         1579
 2019-02-21 06:00:00         1189
 2019-02-21 06:15:00         1110
 2019-02-21 06:30:00         1620
 2019-02-21 06:45:00          803
 2019-02-21 07:00:00          746
 2019-02-21 07:15:00          688
 2019-02-21 07:30:00          708
 ...                          ...
 2019-02-21 16:30:00          876
 2019-02-21 16:45:00          712
 2019-02-21 17:00:00         1420
 2019-02-21 17:15:00         2172
 2019-02-21 17:30:00         2061
 2019-02-21 17:45:00         1857
 2019-02-21 18:00:00         1860
 2019-02-21 18:15:00         3579
 2019-02-21 18:30:00         3455
 2019-02-21 18:45:00         3251
 2019-02-21 19:00:00         3234
 2019-02-21 19:15:00         2616
 2019-02-21 19:30:00         2521
 2019-02-21 19:45:00         2520
 2019-02-21 20:00:00         3422
 2019-02-21 20:15:00         3185
 2019-02-21 20:30:00         3712
 2019-02-21 20:45:00         2944
 2019-02-21 21:00:00         3059
 2019-02-21 21:15:00         3146
 2019-02-21 21:30:00         2953
 2019-02-21 21:45:00         2682
 2019-02-21 22:00:00         2411
 2019-02-21 22:15:00         2638
 2019-02-21 22:30:00         2438
 2019-02-21 22:45:00         2879
 2019-02-21 23:00:00         2909
 2019-02-21 23:15:00         2485
 2019-02-21 23:30:00         2310
 2019-02-21 23:45:00         2436

 [95 rows x 1 columns],                      Consumption
 Time
 2019-02-21 00:15:00         2576
 2019-02-21 00:30:00         3093
 2019-02-21 00:45:00         3448
 2019-02-21 01:00:00         3715
 2019-02-21 01:15:00         2978
 2019-02-21 01:30:00         3086
 2019-02-21 01:45:00         2666
 2019-02-21 02:00:00         2628
 2019-02-21 02:15:00         2274
 2019-02-21 02:30:00         2053
 2019-02-21 02:45:00         2226
 2019-02-21 03:00:00         2214
 2019-02-21 03:15:00         1931
 2019-02-21 03:30:00         1952
 2019-02-21 03:45:00         2143
 2019-02-21 04:00:00         1780
 2019-02-21 04:15:00         1735
 2019-02-21 04:30:00         1676
 2019-02-21 04:45:00         1913
 2019-02-21 05:00:00         2647
 2019-02-21 05:15:00         2178
 2019-02-21 05:30:00         2971
 2019-02-21 05:45:00         1872
 2019-02-21 06:00:00         1738
 2019-02-21 06:15:00         1245
 2019-02-21 06:30:00         2504
 2019-02-21 06:45:00         1671
 2019-02-21 07:00:00         1630
 2019-02-21 07:15:00         1464
 2019-02-21 07:30:00         1566
 ...                          ...
 2019-02-21 16:30:00         1535
 2019-02-21 16:45:00         1393
 2019-02-21 17:00:00         2066
 2019-02-21 17:15:00         2843
 2019-02-21 17:30:00         3043
 2019-02-21 17:45:00         2042
 2019-02-21 18:00:00         2444
 2019-02-21 18:15:00         2276
 2019-02-21 18:30:00         3399
 2019-02-21 18:45:00         3633
 2019-02-21 19:00:00         3286
 2019-02-21 19:15:00         4077
 2019-02-21 19:30:00         3380
 2019-02-21 19:45:00         3514
 2019-02-21 20:00:00         3527
 2019-02-21 20:15:00         3116
 2019-02-21 20:30:00         3128
 2019-02-21 20:45:00         3068
 2019-02-21 21:00:00         2862
 2019-02-21 21:15:00         3172
 2019-02-21 21:30:00         2667
 2019-02-21 21:45:00         2630
 2019-02-21 22:00:00         2618
 2019-02-21 22:15:00         2312
 2019-02-21 22:30:00         2530
 2019-02-21 22:45:00         2210
 2019-02-21 23:00:00         2532
 2019-02-21 23:15:00         3236
 2019-02-21 23:30:00         3211
 2019-02-21 23:45:00         3235

 [95 rows x 1 columns],                      Consumption
 Time
 2019-02-21 00:15:00         3167
 2019-02-21 00:30:00         2893
 2019-02-21 00:45:00         3055
 2019-02-21 01:00:00         2337
 2019-02-21 01:15:00         2917
 2019-02-21 01:30:00         2829
 2019-02-21 01:45:00         2222
 2019-02-21 02:00:00         2065
 2019-02-21 02:15:00         2515
 2019-02-21 02:30:00         2002
 2019-02-21 02:45:00         2282
 2019-02-21 03:00:00         1837
 2019-02-21 03:15:00         1760
 2019-02-21 03:30:00         2083
 2019-02-21 03:45:00         2003
 2019-02-21 04:00:00         1827
 2019-02-21 04:15:00         1662
 2019-02-21 04:30:00         1713
 2019-02-21 04:45:00         1934
 2019-02-21 05:00:00         3205
 2019-02-21 05:15:00         2865
 2019-02-21 05:30:00         2985
 2019-02-21 05:45:00         1214
 2019-02-21 06:00:00         1096
 2019-02-21 06:15:00         1029
 2019-02-21 06:30:00         1666
 2019-02-21 06:45:00         1000
 2019-02-21 07:00:00          843
 2019-02-21 07:15:00          729
 2019-02-21 07:30:00          716
 ...                          ...
 2019-02-21 16:30:00          970
 2019-02-21 16:45:00          819
 2019-02-21 17:00:00         1036
 2019-02-21 17:15:00         2147
 2019-02-21 17:30:00         2107
 2019-02-21 17:45:00         2140
 2019-02-21 18:00:00         1945
 2019-02-21 18:15:00         3024
 2019-02-21 18:30:00         2925
 2019-02-21 18:45:00         2335
 2019-02-21 19:00:00         2683
 2019-02-21 19:15:00         2896
 2019-02-21 19:30:00         2264
 2019-02-21 19:45:00         2512
 2019-02-21 20:00:00         3281
 2019-02-21 20:15:00         2978
 2019-02-21 20:30:00         3940
 2019-02-21 20:45:00         2655
 2019-02-21 21:00:00         2471
 2019-02-21 21:15:00         3007
 2019-02-21 21:30:00         3241
 2019-02-21 21:45:00         3105
 2019-02-21 22:00:00         2638
 2019-02-21 22:15:00         2667
 2019-02-21 22:30:00         2336
 2019-02-21 22:45:00         2544
 2019-02-21 23:00:00         2372
 2019-02-21 23:15:00         2159
 2019-02-21 23:30:00         3102
 2019-02-21 23:45:00         2672

 [85 rows x 1 columns],                      Consumption
 Time
 2019-02-21 00:15:00         3463
 2019-02-21 00:30:00         3231
 2019-02-21 00:45:00         2818
 2019-02-21 01:00:00         2610
 2019-02-21 01:15:00         2725
 2019-02-21 01:30:00         2361
 2019-02-21 01:45:00         2525
 2019-02-21 02:00:00         2246
 2019-02-21 02:15:00         2116
 2019-02-21 02:30:00         2435
 2019-02-21 02:45:00         2241
 2019-02-21 03:00:00         2246
 2019-02-21 03:15:00         2136
 2019-02-21 03:30:00         2061
 2019-02-21 03:45:00         1755
 2019-02-21 04:00:00         1696
 2019-02-21 04:15:00         1947
 2019-02-21 04:30:00         2454
 2019-02-21 04:45:00         2218
 2019-02-21 05:00:00         2234
 2019-02-21 05:15:00         2962
 2019-02-21 05:30:00         1884
 2019-02-21 05:45:00         1753
 2019-02-21 06:00:00         1169
 2019-02-21 06:15:00         1523
 2019-02-21 06:30:00         1928
 2019-02-21 06:45:00         1009
 2019-02-21 07:00:00          741
 2019-02-21 07:15:00          700
 2019-02-21 07:30:00          794
 ...                          ...
 2019-02-21 16:30:00          901
 2019-02-21 16:45:00          852
 2019-02-21 17:00:00         2000
 2019-02-21 17:15:00         2642
 2019-02-21 17:30:00         2823
 2019-02-21 17:45:00         2627
 2019-02-21 18:00:00         2345
 2019-02-21 18:15:00         3902
 2019-02-21 18:30:00         3245
 2019-02-21 18:45:00         2856
 2019-02-21 19:00:00         4133
 2019-02-21 19:15:00         2531
 2019-02-21 19:30:00         2425
 2019-02-21 19:45:00         2579
 2019-02-21 20:00:00         4162
 2019-02-21 20:15:00         3176
 2019-02-21 20:30:00         4548
 2019-02-21 20:45:00         3802
 2019-02-21 21:00:00         3348
 2019-02-21 21:15:00         3104
 2019-02-21 21:30:00         2888
 2019-02-21 21:45:00         2750
 2019-02-21 22:00:00         2850
 2019-02-21 22:15:00         2958
 2019-02-21 22:30:00         2848
 2019-02-21 22:45:00         2866
 2019-02-21 23:00:00         2498
 2019-02-21 23:15:00         3373
 2019-02-21 23:30:00         3050
 2019-02-21 23:45:00         3330

 [95 rows x 1 columns],                      Consumption
 Time
 2019-02-21 00:15:00         3415
 2019-02-21 00:30:00         3718
 2019-02-21 00:45:00         3200
 2019-02-21 01:00:00         2698
 2019-02-21 01:15:00         2701
 2019-02-21 01:30:00         2577
 2019-02-21 01:45:00         2583
 2019-02-21 02:00:00         2636
 2019-02-21 02:15:00         2306
 2019-02-21 02:30:00         1848
 2019-02-21 02:45:00         2233
 2019-02-21 03:00:00         2044
 2019-02-21 03:15:00         1948
 2019-02-21 03:30:00         2149
 2019-02-21 03:45:00         1818
 2019-02-21 04:00:00         1637
 2019-02-21 04:15:00         1362
 2019-02-21 04:30:00         1820
 2019-02-21 04:45:00         1541
 2019-02-21 05:00:00         1530
 2019-02-21 05:15:00         1841

In [69]:
data[0]

                     Consumption
Time
2019-02-21 00:15:00         2291
2019-02-21 00:30:00         1129
2019-02-21 00:45:00         1126
2019-02-21 01:00:00         1631
2019-02-21 01:15:00         1084
2019-02-21 01:30:00         1148
2019-02-21 01:45:00         1214
2019-02-21 02:00:00         1040
2019-02-21 02:15:00         1577
2019-02-21 02:30:00         1007
2019-02-21 02:45:00         1020
2019-02-21 03:00:00         1001
2019-02-21 03:15:00         1031
2019-02-21 03:30:00          950
2019-02-21 03:45:00         1011
2019-02-21 04:00:00          921
2019-02-21 04:15:00          748
2019-02-21 04:30:00         1410
2019-02-21 04:45:00          985
2019-02-21 05:00:00         2302
2019-02-21 05:15:00         2171
2019-02-21 05:30:00         2230
2019-02-21 05:45:00         2110
2019-02-21 06:00:00         1312
2019-02-21 06:15:00         1290
2019-02-21 06:30:00         2154
2019-02-21 06:45:00          906
2019-02-21 07:00:00          968
2019-02-21 07:15:00         1122
2019-02-21 07:30:00         1003
...                          ...
2019-02-21 16:30:00          920
2019-02-21 16:45:00          785
2019-02-21 17:00:00         1529
2019-02-21 17:15:00         1434
2019-02-21 17:30:00         1484
2019-02-21 17:45:00         1330
2019-02-21 18:00:00         1468
2019-02-21 18:15:00         2714
2019-02-21 18:30:00         1442
2019-02-21 18:45:00         1701
2019-02-21 19:00:00         1625
2019-02-21 19:15:00         1868
2019-02-21 19:30:00         2655
2019-02-21 19:45:00         2859
2019-02-21 20:00:00         3800
2019-02-21 20:15:00         2909
2019-02-21 20:30:00         2296
2019-02-21 20:45:00         1995
2019-02-21 21:00:00         1966
2019-02-21 21:15:00         2157
2019-02-21 21:30:00         1670
2019-02-21 21:45:00         1828
2019-02-21 22:00:00         1980
2019-02-21 22:15:00         1804
2019-02-21 22:30:00         1714
2019-02-21 22:45:00         1680
2019-02-21 23:00:00         1611
2019-02-21 23:15:00         1739
2019-02-21 23:30:00         1469
2019-02-21 23:45:00         4176

[95 rows x 1 columns]