In [1]:
from statsmodels.tsa.api import ExponentialSmoothing, SimpleExpSmoothing, Holt

In [ ]:
import pandas as pd

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format='retina'

In [ ]:
from matplotlib.ticker import FuncFormatter

In [ ]:
pd.set_option('display.max_rows',100)

In [ ]:
predict_date='2018_12_23'

## Consumption_afterPV mode peakload already reduced from discharge but mode dutycycle not reduced

In [ ]:
num_day=30

predict_day=int(predict_date[8:])
predict_month=int(predict_date[5:7])
predict_year=int(predict_date[0:4])

str(predict_year)+'_'+str(predict_month)+'_'+str(predict_day)

daybefore=[]
pmb=predict_month-1
dayleft=num_day-predict_day

if predict_day>=num_day:
    day=predict_day-num_day
    while day<predict_day:
        daybefore.append(str(predict_year)+'_'+str(predict_month).zfill(2)+'_'+str(day).zfill(2))
        day+=1
else:
    if pmb==1 or pmb==3 or pmb==5 or pmb==7 or pmb==8 or pmb==10 or pmb==12:
        for i in range(31-dayleft,32,1):
            daybefore.append(str(predict_year)+'_'+str(pmb).zfill(2)+'_'+str(i).zfill(2))
        for i in range(1,predict_day,1):
            daybefore.append(str(predict_year)+'_'+str(predict_month).zfill(2)+'_'+str(i).zfill(2))
    elif pmb==4 or pmb==6 or pmb==9 or pmb==11:
        for i in range(30-dayleft,31,1):
            daybefore.append(str(predict_year)+'_'+str(pmb).zfill(2)+'_'+str(i).zfill(2))
        for i in range(1,predict_day,1):
            daybefore.append(str(predict_year)+'_'+str(predict_month).zfill(2)+'_'+str(i).zfill(2))
    else:
        if predict_year%4==0:
            for i in range(29-dayleft,30,1):
                daybefore.append(str(predict_year)+'_'+str(pmb).zfill(2)+'_'+str(i).zfill(2))
            for i in range(1,predict_day,1):
                daybefore.append(str(predict_year)+'_'+str(predict_month).zfill(2)+'_'+str(i).zfill(2))
        else:
            for i in range(28-dayleft,29,1):
                daybefore.append(str(predict_year)+'_'+str(pmb).zfill(2)+'_'+str(i).zfill(2))
            for i in range(1,predict_day,1):
                daybefore.append(str(predict_year)+'_'+str(predict_month).zfill(2)+'_'+str(i).zfill(2))

pathlist=[]
for i in daybefore:
    pathlist.append('Energy_Balance_'+str(i))

def clean(path):
    rawdata=pd.read_csv(path+".csv", delimiter=";" )
    deleteindex=rawdata.loc[rawdata.loc[pd.IndexSlice[:,'Battery discharging / Mean values [W] ']]==' '].index
    rawdata.drop(deleteindex,inplace=True)
    rawdata.rename(columns={' ':'Time'},inplace=True)
    rawdata['Time']=rawdata['Time'].str.replace('[^\d]','')
    rawdata['Time']=path[15:19]+path[20:22]+path[23:]+rawdata['Time']
    rawdata['Time']=pd.to_datetime(rawdata.Time)
    rawdata.set_index('Time', inplace=True)
    for i in rawdata.columns:
        if i != 'Direct consumption / Mean values [W] ' and i != 'Battery discharging / Mean values [W] ' and i!='External energy supply / Mean values [W] ' and i != 'PV power generation / Mean values [W]  ':
            rawdata.drop([i],axis=1,inplace=True)
    for i in rawdata.columns:
        rawdata[i].fillna('0',inplace=True)
        rawdata[i]=rawdata[i].apply(lambda x: x.replace(' ', '0'))
        rawdata[i]=rawdata[i].str.replace('\D','').astype(int)
    rawdata['Consumption']=rawdata['Direct consumption / Mean values [W] ']+rawdata['Battery discharging / Mean values [W] ']+rawdata['External energy supply / Mean values [W] ']
    rawdata.rename(columns={'PV power generation / Mean values [W]  ':'Generation'},inplace=True)
    rawdata.drop(['Direct consumption / Mean values [W] ', 'Battery discharging / Mean values [W] ','External energy supply / Mean values [W] '],axis=1,inplace=True)
    rawdata.drop(['Generation'],axis=1,inplace=True)
    return rawdata

rawdata=[]

for i in pathlist:
    df=clean(i)
    rawdata.append(df)
    

data=rawdata[0]
for i in range(num_day-1):
    data=pd.concat([data,rawdata[i+1]])
    

for i in range(data.shape[0]):
    if data.iloc[i,0]==0:
        data.iloc[i,0]=data.iloc[i-96,0]

fit4 = ExponentialSmoothing(data.Consumption, seasonal_periods=96, trend='add' ,seasonal='mul').fit()

fit4.fittedvalues.plot(style='--', color='red')

forecast=fit4.forecast(96)

params=fit4.model.params

In [ ]:
forecast

In [ ]:
Consumption=[]
for i in forecast:
    Consumption.append(i)
Consumption

In [ ]:
predictday=predict_date[0:4]+predict_date[5:7]+predict_date[8:10]
minu=[]
h=[]
m=[]
index=[]
Time=[]
for i in range(1,96):
    minu.append(str((i%4)*15).zfill(2))
    h.append(str(i//4).zfill(2))
for i in range(1,96):
    index.append(predictday+h[i-1]+minu[i-1])
for i in index:
    Time.append(pd.to_datetime(i))
Time.append(pd.to_datetime(predictday+'0000'))
len(Time)
    

    
#pd.to_datetime('201812230010')

## Create Dataframe

In [ ]:
DF = pd.DataFrame()
DF['Consumption']=Consumption
DF['Time']=Time
DF.set_index('Time',inplace=True)
DF

In [ ]:
def dutycyclemode(rawdata,percent_batt):
    batt=percent_batt*96
    Consumption_afterPV=[]
    Charge=[]
    for i in rawdata.index:
        if rawdata.loc[i,'Generation']>=rawdata.loc[i,'Consumption']:
            Charge.append(rawdata.loc[i,'Generation']-rawdata.loc[i,'Consumption'])
            Consumption_afterPV.append(0)
        else:
            Charge.append(0)
            Consumption_afterPV.append(rawdata.loc[i,'Consumption']-rawdata.loc[i,'Generation'])    

    rawdata['Charge']=Charge
    rawdata['Consumption_afterPV']=Consumption_afterPV

    totalcharge=rawdata['Charge'].sum()/4

    datanotstart=rawdata[rawdata.Generation==0]
    dataonlystart=rawdata[rawdata.Generation!=0]
    start_time=dataonlystart.index[0]
    consumption_night=rawdata.loc[:start_time,'Consumption'].sum()/4

    if totalcharge+batt>9600:
        discharge_only_at_night=1
    else:
        discharge_only_at_night=0

    if batt-consumption_night>0.6*9600:
        batt_start=batt-consumption
    else:
        batt_start=0.6*9600


    contactor=[]

    for i in rawdata[rawdata.index[0]:start_time].drop(start_time).index:
        if discharge_only_at_night==1:
            contactor.append(1)
        else:
            contactor.append(0)

    for i in rawdata[start_time:].index:
        if rawdata.loc[i,'Charge'] > 0:
            contactor.append(1)
        elif batt_start+totalcharge <= 9600:
            contactor.append(0)
        else:
            contactor.append(1)

    rawdata['Contactor']=contactor

    remain=totalcharge*4

    rawdata['Discharge']=rawdata['Contactor']*0
    for i in rawdata.index:
        if rawdata.loc[i,'Contactor']==1 and rawdata.loc[i,'Charge']==0:
            if remain >= rawdata.loc[i,'Consumption_afterPV']:
                rawdata.loc[i,'Discharge']= rawdata.loc[i,'Consumption_afterPV']
                remain=remain- rawdata.loc[i,'Consumption_afterPV']
            else:
                rawdata.loc[i,'Discharge']=remain
                remain=0
    return rawdata

In [ ]:
def peakloadmode(rawdata,percent_batt):
    batt=percent_batt*96
    Consumption_afterPV=[]
    Charge=[]
    for i in rawdata.index:
        if rawdata.loc[i,'Generation']>=rawdata.loc[i,'Consumption']:
            Charge.append(rawdata.loc[i,'Generation']-rawdata.loc[i,'Consumption'])
            Consumption_afterPV.append(0)
        else:
            Charge.append(0)
            Consumption_afterPV.append(rawdata.loc[i,'Consumption']-rawdata.loc[i,'Generation'])    

    rawdata['Charge']=Charge
    rawdata['Consumption_afterPV']=Consumption_afterPV

    totalcharge=rawdata['Charge'].sum()

    data=rawdata

    peakloadtotal=0

    for i in range(1,96):
        peakloaddf=data.nlargest(i,columns='Consumption_afterPV').Consumption_afterPV
        #print(peakloaddf)
        peakload=peakloaddf.iloc[i-1:i]
        peakloadtotal += peakload.iloc[0]
       # print(peakload)
        #print(peakloadtotal)
        if peakloadtotal>=totalcharge:
            remain=(peakloadtotal-totalcharge)
            #print(remain)
            for j in peakloaddf.index:
                data.loc[j:j,'Consumption_afterPV']=0
            data.loc[peakload.index,'Consumption_afterPV']=remain
            break

    data['Discharge']=data.Consumption_afterPV*0
    for i in peakloaddf.index:
        data.loc[i:i,'Discharge']=data.loc[i:i,'Consumption']-data.loc[i:i,'Generation']-data.loc[i:i,'Consumption_afterPV']

    Contactor=[]
    for i in data.index:
        if data.loc[i,'Charge']>0:
            Contactor.append(1)
        elif data.loc[i,'Discharge']>0:
            Contactor.append(1)
        else:
            Contactor.append(0)
    data['Contactor']=Contactor
    return data

In [ ]:
import os
import pandas as pd
import json
import datetime

def createDayDataframe(filename):
    path = "tongsdata/"
    filedate = filename.split(".")[0].split("-")

    with open(path + filename, 'r', encoding='utf-8') as fin:
        data_json = json.loads(fin.read())

    #  Create X DataFrame
    todayData = {time: data_json[time]['currently'] for time in data_json}
    todayData_DF = pd.DataFrame(todayData).T

    #  Create y DataFrame
    energyBalanceFilename = "energyBalance/Energy_Balance_{}_{}_{}.csv".format(filedate[0], filedate[1], filedate[2]) #change due to json filename
    energyBalance = pd.read_csv(path + energyBalanceFilename, delimiter=";")

    energyBalance_DF = pd.DataFrame(index=energyBalance.iloc[:-1,0].apply(lambda x: x[2:-1]))
    energyBalance_DF['PV Power Generation'] = energyBalance['PV power generation / Mean values [W]  '].values[:-1]
    energyBalance_DF = energyBalance_DF[energyBalance_DF != ' ']
    energyBalance_DF = energyBalance_DF.dropna()
    
    #  Join X y DataFrame
    data = todayData_DF.join(energyBalance_DF)
    return data

def cleanDataframe(masterDF):
    masterData_cleaned = masterDF.reset_index()
    masterData_cleaned = masterData_cleaned.rename(columns={'index': 'time_of_day'})
    masterData_cleaned = masterData_cleaned[masterData_cleaned['PV Power Generation'].notna()]
    masterData_cleaned['month'] = masterData_cleaned['time'].apply(datetime.datetime.fromtimestamp).apply(lambda x: x.month)
    masterData_cleaned['cloudCover'] = masterData_cleaned['cloudCover'].fillna(value=masterData_cleaned['cloudCover'].mean())
    masterData_cleaned['PV Power Generation'] = masterData_cleaned['PV Power Generation'].apply(lambda x: x.replace(",", "")).astype('float')
    return masterData_cleaned

def featureEngineering(masterDF):
    masterDF = masterDF.drop(columns=['icon', 'summary', 'time', 'windBearing', 'windGust', 'ozone', 'precipIntensity', 'precipProbability','pressure'])
    masterDF = pd.get_dummies(masterDF, columns=['time_of_day', 'precipType', 'uvIndex', 'month']) 
    return masterDF

files = os.listdir("tongsdata/")

#files.remove(".DS_Store")
files.remove("energyBalance")

masterData = pd.DataFrame()

for file in files:
    r = createDayDataframe(file).loc['06:30':'18:00']
    print(file, r.shape)
    masterData = pd.concat([masterData, r], axis=0)
    
masterData = cleanDataframe(masterData)
masterData = featureEngineering(masterData)

features = list(masterData.drop(columns=['PV Power Generation']).columns)

masterData = masterData.dropna()

X = masterData.drop(columns=['PV Power Generation']).astype('float').values
y = masterData['PV Power Generation'].astype('float').values


from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

training_features, testing_features, training_target, testing_target = train_test_split(X, y)

# Average CV score on the training set was:-91867.4890210794
exported_pipeline = RandomForestRegressor(bootstrap=False, max_features=0.3, min_samples_leaf=1, min_samples_split=7, n_estimators=100)

exported_pipeline.fit(training_features, training_target)
results = exported_pipeline.predict(testing_features)

from sklearn.metrics import mean_squared_error, r2_score ,mean_absolute_error
print(mean_squared_error(testing_target, results), 
mean_absolute_error(testing_target, results), 
r2_score(testing_target, results))


def pvpredict(predict_date) :
    path = "tongsdata/"
    filename = predict_date.replace("_",'-') + '.json'

    with open(path + filename, 'r', encoding='utf-8') as fin:
        data_json = json.loads(fin.read())

    todayData = {time: data_json[time]['currently'] for time in data_json}
    todayData_DF = pd.DataFrame(todayData).T
    todayData_DF.index.names=['time_of_day']
    todayData_DF = todayData_DF.loc['06:30':'18:00']
    todayData_DF = todayData_DF.reset_index()
    todayData_DF['month'] = todayData_DF['time'].apply(datetime.datetime.fromtimestamp).apply(lambda x: x.month)
    todayData_DF['cloudCover'] = todayData_DF['cloudCover'].fillna(value=todayData_DF['cloudCover'].mean())
    dropcolumns=['icon', 'summary', 'time', 'windBearing', 'windGust', 'ozone', 'precipIntensity', 'precipProbability','pressure']
    for i in dropcolumns:
        if i in todayData_DF.columns:
            todayData_DF = todayData_DF.drop(columns=[i])
    todayData_DF = pd.get_dummies(todayData_DF, columns=['time_of_day', 'precipType', 'uvIndex', 'month'])
    
    masterData_for_predict = masterData.drop(columns=['PV Power Generation'])
    for i in range(len(masterData_for_predict.columns)) : #drop power balance
        if masterData_for_predict.columns[i] not in todayData_DF.columns:
            todayData_DF.insert(i, masterData.columns[i+1], 0)
    missingvalue = todayData_DF[todayData_DF.isna().any(axis=1)].index
    import math
    for i in missingvalue:
        for j in todayData_DF.columns:
            if math.isnan(todayData_DF.loc[i,j]) :
                todayData_DF.loc[i,j] = (todayData_DF.loc[i-1,j]+todayData_DF.loc[i+1,j])/2
    first_predict = todayData_DF.astype('float').values
    
    results_first_predict = exported_pipeline.predict(first_predict)
    results_first_predict = np.array(results_first_predict).tolist()
    for i in range(25):
        results_first_predict.insert(0,0.0)
    for j in range (24):
        results_first_predict.append(0.0)
    return results_first_predict

In [ ]:
Generation=pvpredict(predict_date)

In [ ]:
DF['Generation']=Generation
DF

## Use Algorithm

In [ ]:
dutycyclemode(DF,100)

## Check Data

In [ ]:
def clean1(path):
    rawdata=pd.read_csv(path+".csv", delimiter=";" )
    deleteindex=rawdata.loc[rawdata.loc[pd.IndexSlice[:,'Battery discharging / Mean values [W] ']]==' '].index
    rawdata.drop(deleteindex,inplace=True)
    rawdata.rename(columns={' ':'Time'},inplace=True)
    rawdata['Time']=rawdata['Time'].str.replace('[^\d]','')
    rawdata['Time']=path[15:19]+path[20:22]+path[23:]+rawdata['Time']
    rawdata['Time']=pd.to_datetime(rawdata.Time)
    rawdata.set_index('Time', inplace=True)
    for i in rawdata.columns:
        if i != 'Direct consumption / Mean values [W] ' and i != 'Battery discharging / Mean values [W] ' and i!='External energy supply / Mean values [W] ' and i != 'PV power generation / Mean values [W]  ':
            rawdata.drop([i],axis=1,inplace=True)
    for i in rawdata.columns:
        rawdata[i].fillna('0',inplace=True)
        rawdata[i]=rawdata[i].apply(lambda x: x.replace(' ', '0'))
        rawdata[i]=rawdata[i].str.replace('\D','').astype(int)
    rawdata['Consumption']=rawdata['Direct consumption / Mean values [W] ']+rawdata['Battery discharging / Mean values [W] ']+rawdata['External energy supply / Mean values [W] ']
    rawdata.rename(columns={'PV power generation / Mean values [W]  ':'Generation'},inplace=True)
    rawdata.drop(['Direct consumption / Mean values [W] ', 'Battery discharging / Mean values [W] ','External energy supply / Mean values [W] '],axis=1,inplace=True)
    return rawdata

In [ ]:
check=clean1('Energy_Balance_'+predict_date)
check

## Replace Missing data with data from previous day

In [ ]:
pmb=predict_month-1
if predict_day>1:
        db=(str(predict_year)+'_'+str(predict_month).zfill(2)+'_'+str(predict_day-1).zfill(2))
else:
    if pmb==1 or pmb==3 or pmb==5 or pmb==7 or pmb==8 or pmb==10 or pmb==12:
        db=(str(predict_year)+'_'+str(pmb).zfill(2)+'_'+str(31).zfill(2))
    elif pmb==4 or pmb==6 or pmb==9 or pmb==11:
        db=(str(predict_year)+'_'+str(pmb).zfill(2)+'_'+str(30).zfill(2))
    else:
        if predict_year%4==0:
            db=(str(predict_year)+'_'+str(pmb).zfill(2)+'_'+str(29).zfill(2))
        else:
            db=(str(predict_year)+'_'+str(pmb).zfill(2)+'_'+str(38).zfill(2))    
dayb=clean1('Energy_Balance_'+db)
for i in range(check.shape[0]):
    if check.iloc[i,1]==0:
        check.iloc[i,0]=dayb.iloc[i,0]
        check.iloc[i,1]=dayb.iloc[i,1]

In [ ]:
check

In [ ]:
check['ForecastGen']=DF['Generation']
check['ForecastCon']=DF['Consumption']

In [ ]:
check

In [ ]:
check[['Generation' ,'ForecastGen']].plot(kind='line', title='PV Generation Forecast').set_ylabel('Watt (W)')

check[['Consumption' ,'ForecastCon']].plot(kind='line', title='Load Consumption Forecast').set_ylabel('Watt (W)')

In [163]:
check['Error']=(abs(check['Generation']-check['ForecastGen'])/check['Generation'])*100

In [164]:
check

,Generation,Consumption,ForecastGen,ForecastCon,Error
Time,,,,,
2018-12-23 00:15:00,0,1840,0.000000,1872.536931,NaN
2018-12-23 00:30:00,0,1658,0.000000,1899.528033,NaN
2018-12-23 00:45:00,0,1806,0.000000,1741.427878,NaN
2018-12-23 01:00:00,0,1672,0.000000,1707.801269,NaN
2018-12-23 01:15:00,0,1509,0.000000,1724.591362,NaN
2018-12-23 01:30:00,0,1429,0.000000,1594.332950,NaN
2018-12-23 01:45:00,0,1806,0.000000,1435.385801,NaN
2018-12-23 02:00:00,0,1675,0.000000,1496.983782,NaN
2018-12-23 02:15:00,0,1429,0.000000,1405.141933,NaN
2018-12-23 02:30:00,0,1514,0.000000,1384.723630,NaN
2018-12-23 02:45:00,0,1339,0.000000,1361.210887,NaN
2018-12-23 03:00:00,0,1204,0.000000,1280.089116,NaN
2018-12-23 03:15:00,0,1434,0.000000,1311.775517,NaN
2018-12-23 03:30:00,0,1232,0.000000,1282.837373,NaN
2018-12-23 03:45:00,0,1216,0.000000,1268.520762,NaN
2018-12-23 04:00:00,0,1407,0.000000,1207.936751,NaN
2018-12-23 04:15:00,0,1387,0.000000,1244.575524,NaN
2018-12-23 04:30:00,0,1237,0.000000,1210.225376,NaN
2018-12-23 04:45:00,0,1246,0.000000,1348.412166,NaN
2018-12-23 05:00:00,0,1544,0.000000,1939.045263,NaN
2018-12-23 05:15:00,0,2082,0.000000,1914.795021,NaN
2018-12-23 05:30:00,0,3096,0.000000,2273.562201,NaN
2018-12-23 05:45:00,0,1432,0.000000,1494.674339,NaN
2018-12-23 06:00:00,0,1359,0.000000,1189.830042,NaN
2018-12-23 06:15:00,0,1117,0.000000,1184.734397,NaN
2018-12-23 06:30:00,0,1737,27.443500,1721.011490,inf
2018-12-23 06:45:00,0,1138,28.954333,1075.098388,inf
2018-12-23 07:00:00,3,1417,34.179000,1040.509461,1039.300000
2018-12-23 07:15:00,74,1164,105.880500,1014.814362,43.081757
2018-12-23 07:30:00,148,1179,178.013333,1033.889218,20.279279
2018-12-23 07:45:00,267,2465,242.109333,1187.122517,9.322347
2018-12-23 08:00:00,374,1704,420.528667,1220.412976,12.440820
2018-12-23 08:15:00,485,1216,530.492333,1012.305473,9.379863
2018-12-23 08:30:00,784,1132,762.491333,1046.437204,2.743452
2018-12-23 08:45:00,921,990,989.681000,1002.983060,7.457220
2018-12-23 09:00:00,1170,966,1157.978667,998.588443,1.027464
2018-12-23 09:15:00,1068,1573,1088.087333,1193.297711,1.880836
2018-12-23 09:30:00,924,1027,878.540833,1101.913571,4.919823
2018-12-23 09:45:00,1063,959,990.628833,1053.660415,6.808200
2018-12-23 10:00:00,809,961,909.848667,1018.339195,12.465843
2018-12-23 10:15:00,1249,921,1343.321500,1218.639141,7.551761
2018-12-23 10:30:00,1719,2238,1717.462000,1292.178865,0.089471
2018-12-23 10:45:00,1424,1311,1829.910500,1312.318969,28.504951
2018-12-23 11:00:00,2039,1042,1905.002833,1322.224062,6.571710
2018-12-23 11:15:00,2328,1155,1876.370000,1231.581879,19.399914
2018-12-23 11:30:00,1802,1651,1857.887667,1240.556745,3.101424
2018-12-23 11:45:00,1850,1164,1814.700833,1101.154460,1.908063
2018-12-23 12:00:00,1906,1030,1887.092167,1084.821527,0.992016
2018-12-23 12:15:00,1860,1234,1889.708833,1219.312078,1.597249
2018-12-23 12:30:00,1914,1255,1881.300833,1352.353210,1.708420
2018-12-23 12:45:00,1861,1419,1875.386167,1639.442929,0.773034
2018-12-23 13:00:00,1835,1489,1952.767833,2019.984888,6.417866
2018-12-23 13:15:00,2332,2372,1907.250167,2090.983397,18.213972
2018-12-23 13:30:00,2215,2442,2140.604500,2124.658067,3.358713
2018-12-23 13:45:00,2138,2186,2104.962333,2278.087164,1.545260
2018-12-23 14:00:00,2022,2125,1880.903833,2195.488023,6.978050
2018-12-23 14:15:00,1838,2200,1816.849500,2072.412114,1.150734
2018-12-23 14:30:00,1521,2653,1529.107167,2146.394011,0.533016
2018-12-23 14:45:00,1382,2457,1577.050000,2113.324685,14.113603
2018-12-23 15:00:00,1069,2752,1052.616500,2074.388760,1.532601
2018-12-23 15:15:00,1067,2637,1112.859833,2211.448327,4.298016
2018-12-23 15:30:00,1022,1453,948.291167,1844.565290,7.212215
2018-12-23 15:45:00,900,1457,875.860000,1187.410262,2.682222
2018-12-23 16:00:00,639,1605,608.448000,1150.293363,4.781221
2018-12-23 16:15:00,522,1477,514.177667,1061.895797,1.498531
2018-12-23 16:30:00,353,1367,358.672000,1070.017454,1.606799
2018-12-23 16:45:00,301,1782,300.898333,1056.292055,0.033776
2018-12-23 17:00:00,210,2195,194.055833,1561.273259,7.592460
2018-12-23 17:15:00,144,3291,110.346500,2015.019319,23.370486
2018-12-23 17:30:00,106,3751,89.059167,2036.487957,15.981918
2018-12-23 17:45:00,43,3322,28.438500,1850.255079,33.863953
2018-12-23 18:00:00,4,3517,2.670333,1960.349327,33.241667
2018-12-23 18:15:00,0,3843,0.000000,2146.224631,NaN
2018-12-23 18:30:00,0,3696,0.000000,2306.019723,NaN
2018-12-23 18:45:00,0,3403,0.000000,2257.854812,NaN
2018-12-23 19:00:00,0,3026,0.000000,2499.892778,NaN
2018-12-23 19:15:00,0,3510,0.000000,2895.802795,NaN
2018-12-23 19:30:00,0,3917,0.000000,2681.919675,NaN
2018-12-23 19:45:00,0,3372,0.000000,2619.873484,NaN
2018-12-23 20:00:00,0,2875,0.000000,2730.489097,NaN
2018-12-23 20:15:00,0,2638,0.000000,2679.185995,NaN
2018-12-23 20:30:00,0,2579,0.000000,2709.284898,NaN
2018-12-23 20:45:00,0,2248,0.000000,2745.393005,NaN
2018-12-23 21:00:00,0,2143,0.000000,2576.022239,NaN
2018-12-23 21:15:00,0,2347,0.000000,2488.603811,NaN
2018-12-23 21:30:00,0,2094,0.000000,2160.279179,NaN
2018-12-23 21:45:00,0,1976,0.000000,2074.891982,NaN
2018-12-23 22:00:00,0,1969,0.000000,1975.684341,NaN
2018-12-23 22:15:00,0,1963,0.000000,1938.700327,NaN
2018-12-23 22:30:00,0,1817,0.000000,1897.037554,NaN
2018-12-23 22:45:00,0,1618,0.000000,1883.598449,NaN
2018-12-23 23:00:00,0,1834,0.000000,1972.080690,NaN
2018-12-23 23:15:00,0,1679,0.000000,1841.374608,NaN
2018-12-23 23:30:00,0,1525,0.000000,1918.814272,NaN
2018-12-23 23:45:00,0,1613,0.000000,1917.825326,NaN
2018-12-23 00:00:00,0,1700,0.000000,1889.798379,NaN

## Dont forget to change date

In [166]:
check.loc['2018-12-23 07:30:00':'2018-12-23 17:00:00','Error'].mean()

6.268518431534121